	
/*
Copyright (c) 2001, 2016 Alpha Software Corporation
All Rights Reserved.

This JavaScript library is licensed exclusively for use with Alpha Anywhere, Alpha Five,
Alpha Five Application Server, Alpha Anywhere Application Server,
Alpha Five Run Engine, and Alpha Anywhere Run Engine. It is specifically
not licensed for use on a server that does not have installed on it a
licensed copy of the Alpha Five Application Server or the Alpha Anywhere Application Server.
*/



A5.audio={};A5.audio.Player=Class.create({initialize:function(settings){$u.o.assign(this,{heartbeat:.25,loop:false,onBeforePlay:false,onPlay:false,onPause:false,onChange:false,onBeforeLoad:false,onLoaded:false,onError:false,onDone:false});$u.o.assign(this,settings);this.state={loaded:false,src:false,stream:false,playing:false,buffer:0,current:0,duration:-1,volume:1,muted:false,};this._bhb=0;this._a=document.createElement('audio');this._a.loop=this.loop;$ss(this._a,'position: absolute; top: -1000px;');$e.add(this._a,'loadeddata',this._loaded,this,true);$e.add(this._a,'durationchange',this._durChange,this,true);$e.add(this._a,'playing',this._playing,this,true);$e.add(this._a,'timeupdate',this._timeupdate,this,true);$e.add(this._a,'error',this._error,this,true);document.body.appendChild(this._a);},load:function(src){if(src.constructor!=Array)src=[src];if(this.onBeforeLoad.constructor==Function)this.onBeforeLoad(src);this.state.loaded=false;this.state.stream=false;this.state.buffer=0;if(!(src.length==1&&(src[0]==''||!src[0]))){var types=['aac','ogg','mpeg','mp3','mp4','wav','webm','m4a'];var type='';var exts=[];for(var i=0;i<src.length;i++){if(src[i].substr(0,7)=='stream:'){src[i]=src[i].substr(7);this.state.stream=true;}
type=src[i].split('.').pop().toLowerCase();if(types.indexOf(type)==-1){if(this.state.stream)type='mpeg';else type=false;}else if(type=='m4a')type='mpeg';exts.push(type);}
for(var i=0;i<exts.length;i++){if(exts[i]&&!!this._a.canPlayType&&this._a.canPlayType('audio/'+exts[i])){this.state.src=src[i];if(this.onChange.constructor==Function){this.onChange({type:'buffer'});var ci=this;this._bhb=setInterval(function(){if(ci._a.duration==0||ci._a.duration=='Infinity'){clearInterval(ci._bhb);delete ci;}else{if(ci._a.buffered.length>0){if(ci._a.duration>0){ci.state.buffer=ci._a.buffered.end(0)/ci._a.duration;ci.onChange({type:'buffer'});}
if(Math.round(ci._a.buffered.end(0))>=Math.round(ci._a.duration)){clearInterval(ci._bhb);delete ci;}}}},this.heartbeat*1000);}
this._a.src=src[i];return true;}}
console.log('ERROR: A5.audio.Player.load() - file type not supported - if an audio stream include "stream:" at the beginning of the url.');}
this._a.src='';this.state.src=false;return false;},play:function(){if(this._a.paused&&this.state.src){if(this.onBeforePlay.constructor==Function)this.onBeforePlay();this._a.loop=this.loop;this.state.playing=true;if(this._a.currentTime>=this._a.duration&&this._a.duration>0)this.seek(0);this._a.play();}},pause:function(){if(!this._a.paused&&this.state.src){this.state.playing=false;this._a.pause();if(this.onPause.constructor==Function)this.onPause();}},togglePlay:function(){if(this._a.paused)this.play();else this.pause();},stop:function(){if(this.state.src){this.state.playing=false;this._a.currentTime=0;this._a.pause();this._a.currentTime=0;if(this.onDone.constructor==Function){this.getState();this.onDone({type:'stop'});}}},seek:function(time){if(this.state.src)this._a.currentTime=time;},volume:function(val){this.state.volume=Math.max(Math.min(1,Number(val)),0);this._a.volume=this.state.volume;},mute:function(val){this.state.muted=val;this._a.muted=val;},getState:function(){this.state.current=this._a.currentTime;this.state.duration=this._a.duration;this.state.volume=this._a.volume;this.state.muted=this._a.muted;return this.state;},_loaded:function(){this.state.loaded=true;this.state.buffer=1;clearInterval(this._bhb);if(this.onLoaded.constructor==Function){this.getState();this.onLoaded();}},_error:function(){clearInterval(this._bhb);if(this.onError.constructor==Function)this.onError();},_durChange:function(){if(!this.state.loaded){clearInterval(this._bhb);this.state.loaded=true;this.state.buffer=1;this.onLoaded();}
if(this.onChange.constructor==Function){this.state.duration=this._a.duration;this.onChange({type:'durationchange'});}},_playing:function(){clearInterval(this._bhb);if(this.onPlay.constructor==Function){this.getState();if(!this.state.loaded){this.state.loaded=true;this.state.buffer=1;this.onLoaded();}
this.onPlay();}},_timeupdate:function(){if(this.onChange.constructor==Function){this.state.current=this._a.currentTime;this.onChange({type:'timeupdate'});}
if(this._a.currentTime>=this._a.duration&&this._a.duration>0&&this.state.playing&&!this._a.loop){this.state.playing=false;this._a.pause();if(this.onDone.constructor==Function){this.getState();this.onDone({type:'end'});}}}});A5.audio.recorder={testMode:false};A5.audio.Recorder=Class.create({initialize:function(settings){$u.o.assign(this,{heartbeat:.25,maxDuration:-1,fidelity:'mid',onStart:false,onChange:false,onPause:false,onResume:false,onMaximum:false,onSaved:false,onError:false,onDone:false});$u.o.assign(this,settings);this.state={active:false,src:false,recording:false,level:0,current:0,duration:-1};this._hb=0;this._m=false;this._pg=false;if(typeof window.cordova=='undefined'){if(!A5.audio.recorder.testMode)console.log('ERROR: A5.audio.Recorder - cannot record - not using PhoneGap');else console.log('NOTE: A5.audio.Recorder - in "test" mode - cannot record, but will fire events');}else{var flagAudio=_phoneGapSettings().plugins['cordova-media-with-compression'];if(flagAudio!='npm')alert('ERROR: A5.audio.Recorder - "media with compression" plugin not loaded');else this._pg=true;}
this._lt=0;this._src='';this._save=false;},start:function(){if(this.state.active){this.resume();return false;}
this.state.active=true;this.state.src=false;this.state.recording=true;this.state.level=0;this.state.current=0;this.state.duration=this.maxDuration;this._lt=Date.now();this._save=false;if(this._pg){if(device.platform=='iOS')this._src='cdvfile://localhost/temporary/A5RecorderTemp.m4a';else this._src=cordova.file.externalDataDirectory+'A5RecorderTemp.m4a';var ci=this;this._m=new Media(this._src,function(){ci._m.release();clearInterval(ci._hb);if(ci._save){var err=function(){if(ci.onError.constructor==Function)ci.onError({type:'save'});if(ci.onDone.constructor==Function)ci.onDone({type:'save'});ci.state.src=false;delete ci;console.log('ERROR: A5.audio.Recorder - cannot save file.');}
window.resolveLocalFileSystemURL(ci._src,function(fileEntry){var tfn=fileEntry.toURL();A5.phoneGap.ensureDirPathURL(cordova.file.dataDirectory,'AlphaTemp/audio',function(){A5.phoneGap.copyFileURL(tfn,cordova.file.dataDirectory+'/AlphaTemp/audio',ci.state.src,function(fileEntry){ci.state.src=fileEntry.toURL();if(ci.onSaved.constructor==Function)ci.onSaved(ci.state.src);if(ci.onDone.constructor==Function)ci.onDone({type:'save'});delete ci;},err);},err);},err);}},function(){ci._m.release();clearInterval(ci._hb);if(ci.onError.constructor==Function)ci.onError({type:'recording'});if(ci.onDone.constructor==Function)ci.onDone({type:'save'});delete ci;console.log('ERROR: A5.audio.Recorder - phonegap cannot record file.');});var sr=16000;var f=this.fidelity.toLowerCase();if(f=='very-high')sr=44100;else if(f=='high')sr=32000;else if(f=='low')sr=12000;else if(f=='very-low')sr=8000;this._m.startRecordWithCompression({SampleRate:sr,NumberOfChannels:1});}else if(!A5.audio.recorder.testMode)alert('ERROR: A5.audio.Recorder - cannot record - not using PhoneGap');if(this.onStart.constructor==Function)this.onStart();this._startHB();},pause:function(){if(this.state.recording&&this.state.active){this.state.recording=false;clearInterval(this._hb);var ct=Date.now();this.state.current+=(ct-this._lt)/1000;this.state.current=Math.round(this.state.current*1000)/1000;if(this._pg){this._m.pauseRecord();}
if(this.onPause.constructor==Function)this.onPause();}},resume:function(){if(!this.state.recording&&this.state.active){if((this.state.duration>0&&this.state.duration>=this.state.current)||this.state.duration<=0){this.state.recording=true;if(this.onResume.constructor==Function)this.onResume();if(this._pg){this._m.resumeRecord();}
this._lt=Date.now();this._startHB();}}},cancel:function(){if(this.state.active){clearInterval(this._hb);if(this.onDone.constructor==Function)this.onDone({type:'cancel'});if(this._pg){this._m.stopRecord();}
this.state.active=false;this.state.recording=false;}},save:function(){if(this.state.active){var fn=typeof arguments[0]=='string'?arguments[0]:'';if(fn==''){var d=new Date();fn='rec-'+d.getFullYear()+'_'+(d.getMonth()+1)+'_'+d.getDate()+'-'+d.getHours()+'_'+d.getMinutes()+'_'+d.getSeconds()+'-'+String(this.state.current).replace('.','_');}
fn=fn+'.m4a';this.state.src=fn;this._save=true;clearInterval(this._hb);if(this._pg){this._m.stopRecord();}else if(A5.audio.recorder.testMode){if(this.onSaved.constructor==Function)this.onSaved(this.state.src);if(this.onDone.constructor==Function)this.onDone({type:'save'});}
this.state.active=false;this.state.recording=false;}},getState:function(){return this.state;},_startHB:function(){if(this.heartbeat>0){var ci=this;var cioc=ci.onChange.constructor==Function;this._hb=setInterval(function(){var ct=Date.now();ci.state.current+=(ct-ci._lt)/1000;ci.state.current=Math.round(ci.state.current*1000)/1000;if(ci._pg){ci._m.getRecordLevels(function(result){var pl=0;if(device.platform=='iOS')pl=Math.round((result.averagePower)+160*.625)/100;else pl=Math.round(result)/100;ci.state.level=pl;},function(){console.log('ERROR: A5.audio.Recorder - cannot get level');});}else ci.state.level=Math.round(Math.random()*100)/100;if(cioc)ci.onChange();if(ci.state.duration>0){if(ci.state.duration<=ci.state.current){if(ci.onMaximum.constructor==Function){ci.pause();ci.onMaximum();}else ci.save();}}
ci._lt=ct;},this.heartbeat*1000);}}});