	
/*
Copyright (c) 2001, 2016 Alpha Software Corporation
All Rights Reserved.

This JavaScript library is licensed exclusively for use with Alpha Anywhere, Alpha Five,
Alpha Five Application Server, Alpha Anywhere Application Server,
Alpha Five Run Engine, and Alpha Anywhere Run Engine. It is specifically
not licensed for use on a server that does not have installed on it a
licensed copy of the Alpha Five Application Server or the Alpha Anywhere Application Server.
*/



A5.controlBar={disclosure:{defaultContainer:''},items:{'html':{initialize:function(name,id,s,theme){$u.o.assign(s,{size:'',html:'',bind:{show:''}},true);var html=s.html;html='<div class="A5ControlBarItem" style="'+$if(s.size!='','A5CONTROLBARITEMSIZE: '+s.size+';','')+'">'+html+'</div>';if(s.bind.show!=''){html='{*if '+s.bind.show+'}'+html+'{*endif}';}
s.template=html;}},'button':{initialize:function(name,id,s,theme){$u.o.assign(s,{size:'',settings:{theme:theme,style:''},actions:{},bind:{show:'',disabled:''},autoHideDisclosure:'auto'},true);s.settings.style='width: 100%;'+s.settings.style;if(s.size!='')s.settings.style='A5CONTROLBARITEMSIZE: 100%;'+s.settings.style;var html=A5.buttons.html(id,s.settings,'a5-item="'+name+'"','',true);if(s.bind.disabled!=''){var dHTML=A5.buttons.html(id,s.settings,'a5-item="'+name+'"','disabled',true);html='{*if '+s.bind.disabled+'}'+dHTML+'{*else}'+html+'{*endif}';}
html='<div class="A5ControlBarItem" style="'+$if(s.size!='','A5CONTROLBARITEMSIZE: '+s.size+';','')+'">'+html+'</div>';if(s.bind.show!=''){html='{*if '+s.bind.show+'}'+html+'{*endif}';}
s.template=html;},event:function(type,name,value,item,ele,e){if(type=='down'){var id=ele.id;var pcn=item.settings.pressedClassName;if(pcn!='')$acn(ele,pcn);if(item.settings.pressedIcon!=''){A5.u.icon.update($(ele.id+'.ICON'),item.settings.pressedIcon);A5.buttons._p[id]={c:pcn,i:item.settings.icon};}else A5.buttons._p[id]=pcn;}
if(item.actions[type]){var data={item:{name:name,def:item},element:ele,event:e}
this.action(item.actions[type],data);}}},'button-toggle':{initialize:function(name,id,s,theme){$u.o.assign(s,{size:'',settings:{theme:theme,style:'',type:'two-state',keepPressed:true},actions:{},bind:{value:'',data:'',show:'',disabled:''},autoHideDisclosure:'auto'},true);s.settings.style='width: 100%;'+s.settings.style;if(s.size!='')s.settings.style='A5CONTROLBARITEMSIZE: 100%;'+s.settings.style;if(s.settings.type=='multi-state'){var sStr=JSON.stringify(s.settings);sStr=sStr.replace(/\{/g,'\\{');sStr=sStr.replace(/\}/g,'\\}');sStr=sStr.replace(/:/g,'\\:');html='{A5.buttons.html(\''+id+'\',function(od)\\{var o = '+sStr+'; $u.o.assign(o,od); return o;\\}('+s.bind.data+'['+s.bind.value+']),\'a5-item="'+name+'"\')}';}else{var html=A5.buttons.html(id,s.settings,'a5-item="'+name+'"','',true);if(s.settings.keepPressed){html='{*if '+s.bind.value+'}'+A5.buttons.html(id,s.settings,'a5-item="'+name+'"','pressed',true)+'{*else}'+html+'{*endif}';}
if(s.bind.disabled!=''){var dHTML=A5.buttons.html(id,s.settings,'a5-item="'+name+'"','disabled',true);html='{*if '+s.bind.disabled+'}'+dHTML+'{*else}'+html+'{*endif}';}}
html='<div class="A5ControlBarItem" style="'+$if(s.size!='','A5CONTROLBARITEMSIZE: '+s.size+';','')+'">'+html+'</div>';if(s.bind.show!=''){html='{*if '+s.bind.show+'}'+html+'{*endif}';}
s.template=html;},event:function(type,name,value,item,ele,e){if(type=='down'){var id=ele.id;var pcn=item.settings.pressedClassName;if(pcn!='')$acn(ele,pcn);if(item.settings.pressedIcon!=''){A5.u.icon.update($(ele.id+'.ICON'),item.settings.pressedIcon);A5.buttons._p[id]={c:pcn,i:item.settings.icon};}else A5.buttons._p[id]=pcn;}
if(type=='click'){var curV=A5.u.object.get(this.data,item.bind.value);if(item.settings.type=='multi-state'){curV++;var d=A5.u.object.get(this.data,item.bind.data);if(curV>=d.length)curV=0;this.update(item.bind.value,curV);}else{this.update(item.bind.value,!curV);}}
if(item.actions[type]){var data={item:{name:name,def:item},element:ele,event:e}
this.action(item.actions[type],data);}}},'button-list':{initialize:function(name,id,s,theme){$u.o.assign(s,{size:'',settings:{theme:theme,allowNullSelection:false,multiple:false,className:'',nullSelectionClassName:'',button:{keepPressed:true}},actions:{},bind:{data:'',value:'',show:''},autoHideDisclosure:'auto'},true);A5.themes.assign(s.settings,s.settings.theme,'buttonList');var sStr=JSON.stringify(s.settings);sStr=sStr.replace(/\{/g,'\\{');sStr=sStr.replace(/\}/g,'\\}');sStr=sStr.replace(/:/g,'\\:');html='{A5.buttonLists.html(\''+id+'\','+sStr+','+s.bind.data+','+$if(s.settings.button.keepPressed,s.bind.value,'\'\'')+',\'a5-item="'+name+'" a5-value="\\{index\\}"\')}';var cStyle='';if(s.size=='')cStyle=' style="display: inline-block;"';if(s.settings.nullSelectionClassName!=''){html='<div class="'+s.settings.className+'{*if ('+s.bind.value+').toString() == \'\'}'+s.settings.nullSelectionClassName+'{*endif}"'+cStyle+'>'+html+'</div>';}else{html='<div class="'+s.settings.className+'"'+cStyle+'>'+html+'</div>';}
html='<div class="A5ControlBarItem" style="'+$if(s.size!='','A5CONTROLBARITEMSIZE: '+s.size+';','')+'">'+html+'</div>';if(s.bind.show!=''){html='{*if '+s.bind.show+'}'+html+'{*endif}';}
s.template=html;},event:function(type,name,value,item,ele,e){if(type=='down'){var id=ele.id;var pcn=item.settings.button.pressedClassName;if(pcn!=''){$acn(ele,pcn);A5.buttons._p[id]=pcn;}}
if(type=='click'){var d=A5.u.object.get(this.data,item.bind.data);var v=d[Number(value)];if(v){if(typeof v=='object'){v=v.value;}
var curV=A5.u.object.get(this.data,item.bind.value);if(item.settings.multiple){if(curV.constructor==Array){var cIndx=curV.indexOf(v);if(cIndx==-1){curV.push(v);v=curV;}else curV.splice(cIndx,1);if(item.settings.allowNullSelection===false&&curV.length==0)v=[v];else v=curV;}else console.log('ERROR - button-list value must be array if multiple select is set to true.');}else{if(item.settings.allowNullSelection===true&&v.toString()==curV.toString()){if(curV.constructor==Array)v=[];else v='';}else if(curV.constructor==Array)v=[v];}
this.update(item.bind.value,v);}}
if(item.actions[type]){var data={item:{name:name,def:item},element:ele,event:e}
this.action(item.actions[type],data);}}},'disclosure-button':{initialize:function(name,id,s,theme){$u.o.assign(s,{size:'',disclosure:{name:'',type:''},settings:{show:{theme:theme,style:''},hide:{theme:theme,style:''}},bind:{show:'',disabled:''}},true);s.settings.show.style='width: 100%;'+s.settings.show.style;s.settings.hide.style='width: 100%;'+s.settings.hide.style;if(s.size!=''){s.settings.show.style='A5CONTROLBARITEMSIZE: 100%;'+s.settings.show.style;s.settings.hide.style='A5CONTROLBARITEMSIZE: 100%;'+s.settings.hide.style;}
var showHTML=A5.buttons.html(id,s.settings.show,'a5-item="'+name+'"','',true);var hideHTML=A5.buttons.html(id,s.settings.hide,'a5-item="'+name+'"','',true);if(s.bind.disabled!=''){var dHTML=A5.buttons.html(id,s.settings.show,'a5-item="'+name+'"','disabled',true);showHTML='{*if '+s.bind.disabled+'}'+dHTML+'{*else}'+showHTML+'{*endif}';dHTML=A5.buttons.html(id,s.settings.hide,'a5-item="'+name+'"','disabled',true);hideHTML='{*if '+s.bind.disabled+'}'+dHTML+'{*else}'+hideHTML+'{*endif}';}
var html='{*if [temp].state.disclosure.shown && [temp].state.disclosure.name == \''+s.disclosure.name+'\'}'+hideHTML+'{*else}'+showHTML+'{*endif}';html='<div class="A5ControlBarItem" style="'+$if(s.size!='','A5CONTROLBARITEMSIZE: '+s.size+';','')+'">'+html+'</div>';if(s.bind.show!=''){html='{*if '+s.bind.show+'}'+html+'{*endif}';}
s.template=html;},event:function(type,name,value,item,ele,e){if(type=='down'){var id=ele.id;var pcn=item.settings.pressedClassName;if(pcn!='')$acn(ele,pcn);if(item.settings.pressedIcon!=''){A5.u.icon.update($(ele.id+'.ICON'),item.settings.pressedIcon);A5.buttons._p[id]={c:pcn,i:item.settings.icon};}else A5.buttons._p[id]=pcn;}
if(type=='click'){if(this._d.shown)var html=A5.buttons.html(ele.id,item.settings.hide,'a5-item="'+name+'"','',false);else var html=A5.buttons.html(ele.id,item.settings.show,'a5-item="'+name+'"','',false);var pEle=ele.parentNode;pEle.innerHTML=html;}}}},_:{lDefs:{className:'',before:{items:[]},middle:{items:[]},after:{items:[]}},initDone:false,init:function(){if(!A5.controlBar._.initDone){A5.u.css.setSelector('.A5ControlBarHorz .A5ControlBarLine','position: relative; text-align: center;');A5.u.css.setSelector('.A5ControlBarHorz .A5ControlBarLineBefore','text-align: left;');A5.u.css.setSelector('.A5ControlBarHorz .A5ControlBarLineAfter','text-align: right;');A5.u.css.setSelector('.A5ControlBarHorz .A5ControlBarItem','display: inline-block;');A5.u.css.setSelector('.A5ControlBarHorz .A5ControlBarLineContentBefore','position: absolute; top: 0px; left: 0px;');A5.u.css.setSelector('.A5ControlBarHorz .A5ControlBarLineContentAfter','position: absolute; top: 0px; right: 0px;');A5.u.css.setSelector('.A5ControlBarHorz .A5ControlBarLineBefore .A5ControlBarLineContentBefore, .A5ControlBarHorz .A5ControlBarLineAfter .A5ControlBarLineContentAfter','position: static;');A5.u.css.setSelector('.A5ControlBarCollapse .A5ControlBarHorz .A5ControlBarLine > div','position: static; display: inline;');A5.u.css.setSelector('.A5ControlBarCollapse .A5ControlBarHorz .A5ControlBarLine','text-align: inherit;');A5.u.css.setSelector('.A5ControlBarVert','display: table; height: 100%;');A5.u.css.setSelector('.A5ControlBarVert .A5ControlBarLine','display: table-cell; vertical-align: middle;');A5.u.css.setSelector('.A5ControlBarVert .A5ControlBarLineBefore','display: table-cell; vertical-align: top;');A5.u.css.setSelector('.A5ControlBarVert .A5ControlBarLineAfter','display: table-cell; vertical-align: bottom;');A5.u.css.setSelector('.A5ControlBarVert .A5ControlBarLineContentBefore','position: absolute; top: 0px;');A5.u.css.setSelector('.A5ControlBarVert .A5ControlBarLineContentAfter','position: absolute; bottom: 0px;');A5.u.css.setSelector('.A5ControlBarVert .A5ControlBarLineBefore .A5ControlBarLineContentBefore, .A5ControlBarVert .A5ControlBarLineAfter .A5ControlBarLineContentAfter','position: static;');A5.u.css.setSelector('.A5ControlBarCollapse .A5ControlBarVert .A5ControlBarLine > div','position: static; display: block;');A5.u.css.setSelector('.A5ControlBarCollapse .A5ControlBarVert .A5ControlBarLine','vertical-align: top;');A5.controlBar._.initDone=true;}}}}
A5.ControlBar=Class.create({initialize:function(contId,data,settings){if(typeof settings=='undefined'){settings=data;data=null;}
this.contId=contId;A5.controlBar._.init();$u.o.assign(this,{theme:'',override:'base',edge:'top',topClassName:'',bottomClassName:'',leftClassName:'',rightClassName:'',separator:{horizontalClassName:'',verticalClassName:''},items:{},actions:{},layout:'',layouts:{},disclosure:{container:A5.controlBar.disclosure.defaultContainer,animation:{duration:300,tween:'ease-in-out'},coverClassName:'',cover:{topClassName:'',bottomClassName:'',leftClassName:'',rightClassName:''},extend:{topClassName:'',bottomClassName:'',leftClassName:'',rightClassName:''},expand:{topClassName:'',bottomClassName:'',leftClassName:'',rightClassName:''},defaults:{html:'',className:'',onInitialize:false,onSize:false,onShow:false,onHide:false}},disclosures:{},data:{},state:{layout:'',disclosure:{shown:false,name:'',type:'',edge:''}},onDraw:false,onBeforeDraw:false,onPopulate:false,onBeforePopulate:false,onChange:false});if(typeof settings.theme!='undefined')A5.themes.assign(this,settings.theme,'controlBar');$u.o.assign(this,settings);A5.overrides.assign(this,'controlBar',this.override);this.initializeItems();var cEle=$(contId);if(cEle.style.position!='absolute')cEle.style.position='relative';cEle.style.overflow='hidden';this._bindEvents(cEle);this._m={anim:false,next:{has:false,args:[]},async:{}};var egName='CONTROLBAR.'+this.contId;var dEle=document.createElement('div');dEle.id=this.contId+'.DISCLOSURES';$ss(dEle,'z-index: 100000; position: absolute; top: 0px; left: 0px; right: 0px; bottom: 0px; display: none;');dEle.innerHTML='<div style="position: absolute; overflow: hidden;"><div class="'+this.disclosure.defaults.className+'" id="'+this.contId+'.DISCLOSURE.A5CONTROLBARDYNAMIC" style="z-index: 100002; position: absolute; display: none;"></div></div><div id="'+this.contId+'.DISCLOSURE.CLOSE" style="z-index: 100001; position: absolute; display: none;">&nbsp;</div>';if(this.disclosure.container!='')$(this.disclosure.container).appendChild(dEle);else document.body.insertBefore(dEle,document.body.firstChild);this._bindEvents(dEle.children[0].children[0]);$e.add(dEle,A5.d.evnts.click,this._disClick,this,false,egName);$e.add(this.contId+'.DISCLOSURE.CLOSE',A5.d.evnts.click,this._disCloseClick,this,false,egName);if(A5.flags.supportsTouch){$e.add(dEle,'touchmove',function(e){var tempT=$e.getTouches(e);var pDef=true;if(tempT){if(tempT.length){if(tempT.length>1)pDef=false;}}
if(pDef)$e.preventDefault(e);});}
this._d={ele:dEle,shown:false,current:false,next:false};var cdEle=dEle.children[0];var tdEle=null;var dd=null;for(var d in this.disclosures){dd=this.disclosures[d];$u.o.assign(dd,this.disclosure.defaults,true);tdEle=document.createElement('div');tdEle.id=this.contId+'.DISCLOSURE.'+d;tdEle.className=dd.className;tdEle.innerHTML=dd.html;tdEle.style.position='absolute';tdEle.style.display='none';tdEle.style.zIndex='100002';cdEle.appendChild(tdEle);if(dd.onInitialize.constructor==Function)dd.onInitialize.call(this,tdEle);}
if(data!=null)this.populate(data);else this.refresh();if(!A5.flags.isMobile)$e.add(window,'resize',this._resizeDis,this,true,egName);else{$e.add(window,'orientationchange',this._resizeDis,this,true,egName);if(A5.flags.iOSVersion==-1)$e.add(window,'resize',this._resizeDis,this,true,egName);}
$e.add(document,'webkitfullscreenchange',this._resizeDis,this,true,egName);$e.add(document,'mozfullscreenchange',this._resizeDis,this,true,egName);$e.add(document,'fullscreenchange',this._resizeDis,this,true,egName);$e.add(document,'fullscreenchange',this._resizeDis,this,true,egName);},initializeItems:function(){var iObj=null;var iTObj=null;var theme=this.theme;theme=theme.split(':').shift();for(var item in this.items){iObj=this.items[item];iTObj=A5.controlBar.items[iObj.type];if(iTObj)iTObj.initialize(item,this.contId+'.'+item,iObj,theme);else iObj.template='ERROR '+item+' - Item type "'+iObj.type+'" not found!';}
for(var layout in this.layouts){if(typeof this.layouts[layout]._t!='undefined'){delete this.layouts[layout]._t.top;delete this.layouts[layout]._t.bottom;delete this.layouts[layout]._t.left;delete this.layouts[layout]._t.right;}}},destroy:function(){$e.removeGroup('CONTROLBAR.'+this.contId);},populate:function(data){var anim=typeof arguments[1]!='undefined'?arguments[1]:false;var fEvnts=typeof arguments[2]!='undefined'?arguments[2]:true;var async=typeof arguments[3]!='undefined'?arguments[3]:false;if(this.onBeforePopulate.constructor==Function&&fEvnts){var res=this.onBeforePopulate.call(this,data);if(typeof res=='boolean'){if(!res)return false;}}
this.data={};$u.o.assign(this.data,data);this.refresh(anim,async);if(this.onPopulate.constructor==Function&&fEvnts)this.onPopulate.call(this,data);},update:function(p,v){var anim=typeof arguments[2]!='undefined'?arguments[2]:false;var fEvnts=typeof arguments[3]!='undefined'?arguments[3]:true;var async=typeof arguments[4]!='undefined'?arguments[4]:false;if(typeof p=='string'){p=[p];v=[v];}
for(var i=0;i<p.length;i++)A5.u.object.set(this.data,p[i],v[i]);if(fEvnts){if(this.onChange.constructor==Function)this.onChange.call(this,p,v);}
this.refresh(anim,async);},setLayout:function(l){if(this.layouts[l]){var anim=typeof arguments[1]!='undefined'?arguments[1]:false;var async=typeof arguments[2]!='undefined'?arguments[2]:false;this.layout=l;this.refresh(anim,async);}else console.log('ERROR - control bar layout "'+l+'" not found');},refresh:function(){var anim=typeof arguments[0]!='undefined'?arguments[0]:false;var async=typeof arguments[1]!='undefined'?arguments[1]:false;if(this._m.anim){this._m.next.has=true;this._m.next.args=[anim,async];return false;}
if(async){clearTimeout(this._m.async.to);var ci=this;this._m.async.to=setTimeout(function(){ci.refresh.apply(ci,ci._m.async.args);delete ci;},0);this._m.async.args=[anim];return false;}
if(this.onBeforeDraw.constructor==Function)this.onBeforeDraw.call(this,'main');var l='';if(this.layout.constructor==Function)l=this.layout.call(this);else l=this.layout;this._cl=this.layouts[l];this.state.layout=l;this._compileTemplate(this._cl,this.edge);var cEle=$(this.contId);var html=A5.u.template.expand(this.data,{template:this._cl._t[this.edge]},{state:this.state});var animDo=false;var cn='class="'+this[this.edge+'ClassName']+'" ';var hCSS='';if(this.edge=='left'||this.edge=='right')hCSS=' height: 100%;';if(anim){if(typeof anim!='object')anim={type:anim,duration:500};if(!anim.tween)anim.tween='ease-in-out';if(anim.type.indexOf('-in')!=-1||anim.type.indexOf('-out')!=-1||anim.type.indexOf('-before')!=-1||anim.type.indexOf('-after')!=-1){if(this.edge=='top'){anim.type=anim.type.replace('-in','-top').replace('-out','-bottom').replace('-before','-left').replace('-after','-right');}else if(this.edge=='bottom'){anim.type=anim.type.replace('-in','-bottom').replace('-out','-top').replace('-before','-left').replace('-after','-right');}else if(this.edge=='left'){anim.type=anim.type.replace('-in','-left').replace('-out','-right').replace('-before','-top').replace('-after','-bottom');}else if(this.edge=='right'){anim.type=anim.type.replace('-in','-right').replace('-out','-left').replace('-before','-top').replace('-after','-bottom');}}
var oldHTML='';var ccEle=$(this.contId+'.CONTENT');if(ccEle){oldHTML=ccEle.innerHTML;oldHTML=oldHTML.replace(/id="[^"]+"/g,'').replace(/a5-item="[^"]+"/g,'');}
var tProp=A5.u.css.properties.transform;var tPropDOM=A5.u.css.properties.transformDOM;var taProp=tProp.replace('transform','transition');if(anim.type.indexOf('slide-')==0){var vals=['0px','100%','0px','-100%'];if(anim.type=='slide-left')vals=['100%','0px','-100%','0px'];else if(anim.type=='slide-right')vals=['-100%','0px','100%','0px'];else if(anim.type=='slide-bottom')vals=['0px','-100%','0px','100%'];var taVal=taProp+': '+tProp+' '+anim.duration+'ms '+anim.tween+';';html='<div '+cn+'id="'+this.contId+'.CONTENTOLD" style="position: absolute; width: 100%;'+hCSS+' '+tProp+': '+A5.u.css.transform2D('0px','0px')+'; '+taVal+'">'+oldHTML+'</div><div '+cn+'id="'+this.contId+'.CONTENT" style="'+hCSS+''+tProp+': '+A5.u.css.transform2D(vals[0],vals[1])+'; '+taVal+'">'+html+'</div>';animDo=[{p:tPropDOM,v:A5.u.css.transform2D('0px','0px')},{p:tPropDOM,v:A5.u.css.transform2D(vals[2],vals[3])}];}else if(anim.type.indexOf('swap-')==0){var vals=['0px','-100%'];if(anim.type=='swap-left')vals=['-100%','0px'];else if(anim.type=='swap-right')vals=['100%','0px'];else if(anim.type=='swap-bottom')vals=['0px','100%'];var hDur=(anim.duration/2);var taVal=taProp+': '+tProp+' '+hDur+'ms '+anim.tween+';';html='<div '+cn+'id="'+this.contId+'.CONTENTOLD" style="position: absolute; width: 100%;'+hCSS+' '+tProp+': '+A5.u.css.transform2D('0px','0px')+'; '+taVal+'">'+oldHTML+'</div><div '+cn+'id="'+this.contId+'.CONTENT" style="'+hCSS+''+tProp+': '+A5.u.css.transform2D(vals[0],vals[1])+'; '+taVal+' transition-delay: '+hDur+'ms;">'+html+'</div>';animDo=[{p:tPropDOM,v:A5.u.css.transform2D('0px','0px')},{p:tPropDOM,v:A5.u.css.transform2D(vals[0],vals[1])}];}else if(anim.type=='fade'){var taVal=taProp+': opacity '+anim.duration+'ms '+anim.tween+';';html='<div '+cn+'id="'+this.contId+'.CONTENTOLD" style="position: absolute; width: 100%;'+hCSS+' opacity: 1; '+taVal+'">'+oldHTML+'</div><div '+cn+'id="'+this.contId+'.CONTENT" style="'+hCSS+'opacity: 0; '+taVal+'">'+html+'</div>';animDo=[{p:'opacity',v:'1'},{p:'opacity',v:'0'}];}else html='<div id="'+this.contId+'.CONTENT" style="'+hCSS+'">'+html+'</div>';}else html='<div '+cn+'id="'+this.contId+'.CONTENT" style="'+hCSS+'">'+html+'</div>';cEle.innerHTML=html;this._m.anim=false;if(animDo){var lcEle=$(this.contId+'.CONTENT');var lcoEle=$(this.contId+'.CONTENTOLD');lcEle.offsetWidth;lcEle.style[animDo[0].p]=animDo[0].v;lcoEle.style[animDo[1].p]=animDo[1].v;var ci=this;setTimeout(function(){var ele=$(ci.contId+'.CONTENTOLD');pEle=ele.parentNode;pEle.removeChild(ele);ci._refreshAnimComplete();delete ci;delete ele;delete pEle;},anim.duration);this._m.anim=true;}
if(this.onDraw.constructor==Function)this.onDraw.call(this,'main',cEle);if(this._d.shown){if(this._d.current.s.name.substr(0,7)=='layout:'){var dEle=$(this.contId+'.DISCLOSURE.A5CONTROLBARDYNAMIC');if(this.onBeforeDraw.constructor==Function)this.onBeforeDraw.call(this,'disclosure');var layoutEdge=this._d.current.layoutEdge;var cn='class="'+this[layoutEdge+'ClassName']+'" ';var hCSS='';if(layoutEdge=='left'||layoutEdge=='right')hCSS='style="height: 100%;"';dEle.innerHTML='<div '+cn+hCSS+'>'+A5.u.template.expand(this.data,{template:this._cdl._t[layoutEdge]},{state:this.state})+'</div>';if(this.onDraw.constructor==Function)this.onDraw.call(this,'disclosure',dEle);}}},action:function(action){if(this.actions[action]){var data=typeof arguments[1]!='undefined'?arguments[1]:false;this.actions[action].call(this,data);}else console.log('ERROR - control bar action "'+action+'" not found');},showDisclosure:function(s){if(this._d.shown){this._d.next=s;this.hideDisclosure();}else{var ele=typeof arguments[1]!='undefined'?arguments[1]:false;ele=$(ele);$u.o.assign(s,{name:'',type:'extend',size:false,animation:true,autoHide:true,className:'',coverClassName:this.disclosure.coverClassName},true);var type=s.type;if(type.indexOf('element')!=-1&&!ele){type=type.split('-').shift();if(type=='expand')type='expand-after';}
this._cdl=false;var dd=false;if(s.name.substr(0,7)=='layout:'){var dEle=$(this.contId+'.DISCLOSURE.A5CONTROLBARDYNAMIC');this._cdl=this.layouts[s.name.substr(7)];if(!this._cdl)return false;if(s.className=='')s.className=this.disclosure.defaults.className;}else{dd=this.disclosures[s.name];if(!dd)return false;var dEle=$(this.contId+'.DISCLOSURE.'+s.name);if(s.className=='')s.className=dd.className;}
dEle.className=s.className;dEle.style.top='';dEle.style.bottom='';dEle.style.left='';dEle.style.right='';dEle.style.width='';dEle.style.height='';if(type=='explicit'){if(s.rectangle.constrcutor==Function)var rect=s.rectangle.call(this,s);else var rect=s.rectangle;}else var rect=this._getDisclosureRect(type,ele);var layoutEdge=this.edge;if(s.name.substr(0,7)=='layout:'){if(type=='outside-before'||type=='outside-after'||type.split('-').shift()=='screen')layoutEdge=rect.edge;this._compileTemplate(this._cdl,layoutEdge);if(this.onBeforeDraw.constructor==Function)this.onBeforeDraw.call(this,'disclosure');var cn='class="'+this[layoutEdge+'ClassName']+'" ';var hCSS='';if(layoutEdge=='left'||layoutEdge=='right')hCSS='style="height: 100%;"';dEle.innerHTML='<div '+cn+hCSS+'>'+A5.u.template.expand(this.data,{template:this._cdl._t[layoutEdge]},{state:this.state})+'</div>';if(this.onDraw.constructor==Function)this.onDraw.call(this,'disclosure',dEle);}
var dcEle=this._d.ele.children[0];if(typeof rect.className!='undefined')dcEle.className=rect.className;else dcEle.className='';dcEle.style.top=rect.top+'px';dcEle.style.bottom=rect.bottom+'px';dcEle.style.left=rect.left+'px';dcEle.style.right=rect.right+'px';dEle.style[rect.edge]='0px';if(rect.fill=='both'||s.size=='fill'){dEle.style.top='0px';dEle.style.bottom='0px';dEle.style.left='0px';dEle.style.right='0px';}else if(rect.fill=='width'){dEle.style.left='0px';dEle.style.right='0px';}else if(rect.fill=='height'){dEle.style.top='0px';dEle.style.bottom='0px';}
var startTrans='';if(rect.edge=='top'){startTrans=A5.u.css.transform2D('0px','-100%');if(s.size&&s.size!='fill'&&type!='cover'){dEle.style.height=s.size;}}else if(rect.edge=='bottom'){startTrans=A5.u.css.transform2D('0px','100%');if(s.size&&s.size!='fill'&&type!='cover'){dEle.style.height=s.size;}}else if(rect.edge=='left'){startTrans=A5.u.css.transform2D('-100%','0px');if(s.size&&s.size!='fill'&&type!='cover'){dEle.style.width=s.size;}}else if(rect.edge=='right'){startTrans=A5.u.css.transform2D('100%','0px');if(s.size&&s.size!='fill'&&type!='cover'){dEle.style.width=s.size;}}
dEle.style.display='';if(type.split('-').shift()=='expand'&&!s.size)this._d.ele.className=s.coverClassName+' A5ControlBarCollapse';else this._d.ele.className=s.coverClassName;var dur=this.disclosure.animation.duration;var tween=this.disclosure.animation.tween;if(s.animation){if(typeof s.animation=='object'){if(s.animation.duration)dur=s.animation.duration;if(s.animation.tween)tween=s.animation.tween;}
var cssDOMProp=A5.u.css.properties.transformDOM;var cssAnimProp=A5.u.css.properties.transitionDOM;dEle.style[cssDOMProp]=startTrans;dEle.style[cssAnimProp]='';this._d.ele.style.display='';dEle.offsetHeight;dEle.style[cssAnimProp]=A5.u.css.properties.transform+' '+dur+'ms '+tween;dEle.style[cssDOMProp]=A5.u.css.transform2D('0px','0px');}else{var cssDOMProp=A5.u.css.properties.transformDOM;var cssAnimProp=A5.u.css.properties.transitionDOM;dEle.style[cssDOMProp]=A5.u.css.transform2D('0px','0px');dEle.style[cssAnimProp]='';this._d.ele.style.display='';dEle.offsetHeight;dEle.style[cssAnimProp]=A5.u.css.properties.transform+' '+dur+'ms '+tween;}
var eleId=false
if(ele)eleId=ele.id;this._d.current={s:s,eleId:eleId,dEle:dEle,trans:startTrans,dur:dur,layoutEdge:layoutEdge,internalShow:false};this._d.next=false;this._d.shown=true;var dbcEle=$(this.contId+'.DISCLOSURE.CLOSE');dbcEle.style.display='none';if(this._d.internalShow&&ele){this._d.current.internalShow=true;var eBRect=ele.getBoundingClientRect();dbcEle.style.top=eBRect.top+'px';dbcEle.style.left=eBRect.left+'px';dbcEle.style.width=eBRect.width+'px';dbcEle.style.height=eBRect.height+'px';dbcEle.style.display='block';}
this.state.disclosure.shown=true;this.state.disclosure.name=s.name;this.state.disclosure.type=type;this.state.disclosure.edge=layoutEdge;if(dd){$e.execute(dEle,'a5resize');if(dd.onShow.constructor==Function)dd.onShow.call(this,dEle);if(dd.onSize.constructor==Function)dd.onSize.call(this,dEle);}}},hideDisclosure:function(){if(this._d.shown){var anim=typeof arguments[0]!='undefined'?arguments[0]:true;if(!anim)this._hideDisclosureComplete();else{this._d.current.dEle.style[A5.u.css.properties.transformDOM]=this._d.current.trans;var ci=this;setTimeout(function(){ci._hideDisclosureComplete();delete ci;},this._d.current.dur);}}},resizeDisclosure:function(){if(this._d.shown){var type=this._d.current.s.type
if(type=='explicit'){if(this._d.current.s.rectangle.constrcutor==Function)var rect=this._d.current.s.rectangle.call(this,this._d.current.s);else var rect=this._d.current.s.rectangle;}else var rect=this._getDisclosureRect(type,$(this._d.current.eleId));var dcEle=this._d.ele.children[0];dcEle.style.top=rect.top+'px';dcEle.style.bottom=rect.bottom+'px';dcEle.style.left=rect.left+'px';dcEle.style.right=rect.right+'px';var dd=this.disclosures[this._d.current.s.name];if(dd){$e.execute(this._d.current.dEle,'a5resize');if(dd.onSize.constructor==Function)dd.onSize.call(this,this._d.current.dEle);}
if(this._d.current.internalShow){var dbcEle=$(this.contId+'.DISCLOSURE.CLOSE');var eBRect=$(this._d.current.eleId).getBoundingClientRect();dbcEle.style.top=eBRect.top+'px';dbcEle.style.left=eBRect.left+'px';dbcEle.style.width=eBRect.width+'px';dbcEle.style.height=eBRect.height+'px';}}},_getDisclosureRect:function(type,ele){var rect={top:0,left:0,right:0,bottom:0,edge:this.edge,fill:'',className:''};var cBRect=$(this.contId).getBoundingClientRect();var eBRect=false;if(ele)eBRect=ele.getBoundingClientRect();if(this.disclosure.container!=''){var tBRect=$(this.disclosure.container).getBoundingClientRect();var leftOff=tBRect.left;var topOff=tBRect.top;var docWidth=tBRect.width;var docHeight=tBRect.height;}else{var leftOff=0;var topOff=0;var docWidth=document.documentElement.clientWidth;var docHeight=document.documentElement.clientHeight;}
if(type.split('-').shift()=='expand'){rect.top=cBRect.top-topOff;rect.bottom=docHeight-cBRect.bottom+topOff;rect.left=cBRect.left-leftOff;rect.right=docWidth-cBRect.right+leftOff;if(this.edge=='top'||this.edge=='bottom'){rect.fill='height';if(type=='expand-before'){rect.edge='left';}else if(type=='expand-after'){rect.edge='right';}else if(type=='expand-element'||type=='expand-element-cover'){if(eBRect.left>(cBRect.left+(cBRect.width/2))){rect.edge='right';if(type=='expand-element')rect.right=(docWidth-eBRect.left+leftOff);else rect.right=(docWidth-eBRect.right+leftOff);}else{rect.edge='left';if(type=='expand-element')rect.left=eBRect.right-leftOff;else rect.left=eBRect.left-leftOff;}}}else{rect.fill='width';if(type=='expand-before'){rect.edge='top';}else if(type=='expand-after'){rect.edge='bottom';}else if(type=='expand-element'||type=='expand-element-cover'){if(eBRect.top>(cBRect.top+(cBRect.height/2))){rect.edge='bottom';if(type=='expand-element')rect.bottom=(docHeight-eBRect.top+topOff);else rect.bottom=(docHeight-eBRect.bottom+topOff);}else{rect.edge='top';if(type=='expand-element')rect.top=eBRect.bottom-topOff;else rect.top=eBRect.top-topOff;}}}
rect.className=this.disclosure.expand[rect.edge+'ClassName'];}else if(type=='cover'){rect.top=cBRect.top-topOff;rect.bottom=docHeight-cBRect.bottom+topOff;rect.left=cBRect.left-leftOff;rect.right=docWidth-cBRect.right+leftOff;rect.fill='both';rect.className=this.disclosure.cover[rect.edge+'ClassName'];}else if(type.split('-').shift()=='screen'){rect.edge=type.split('-').pop();if(rect.edge=='left'||rect.edge=='right')rect.fill='height';else rect.fill='width';}else{if(this.edge=='top'){rect.left=cBRect.left-leftOff;rect.right=docWidth-cBRect.right+leftOff;rect.fill='width';if(type=='extend-element'){rect.top=eBRect.bottom-topOff;}else if(type=='extend-element-cover'){rect.top=eBRect.top-topOff;}else{rect.top=cBRect.bottom-topOff;if(type=='outside-before'){rect.fill='height';rect.edge='left';}else if(type=='outside-after'){rect.fill='height';rect.edge='right';}}}else if(this.edge=='bottom'){rect.left=cBRect.left-leftOff;rect.right=docWidth-cBRect.right+leftOff;rect.fill='width';if(type=='extend-element'){rect.bottom=docHeight-eBRect.top+topOff;}else if(type=='extend-element-cover'){rect.bottom=docHeight-eBRect.bottom+topOff;}else{rect.bottom=docHeight-cBRect.top+topOff;if(type=='outside-before'){rect.fill='height';rect.edge='left';}else if(type=='outside-after'){rect.fill='height';rect.edge='right';}}}else if(this.edge=='left'){rect.top=cBRect.top-topOff;rect.bottom=docHeight-cBRect.bottom+topOff;rect.fill='height';if(type=='extend-element'){rect.left=eBRect.right-leftOff;}else if(type=='extend-element-cover'){rect.left=eBRect.left-leftOff;}else{rect.left=cBRect.right-leftOff;if(type=='outside-before'){rect.fill='width';rect.edge='top';}else if(type=='outside-after'){rect.fill='width';rect.edge='bottom';}}}else if(this.edge=='right'){rect.top=cBRect.top-topOff;rect.bottom=docHeight-cBRect.bottom+topOff;rect.fill='height';if(type=='extend-element'){rect.right=docWidth-eBRect.left+leftOff;}else if(type=='extend-element-cover'){rect.right=docWidth-eBRect.right+leftOff;}else{rect.right=docWidth-cBRect.left+leftOff;if(type=='outside-before'){rect.fill='width';rect.edge='top';}else if(type=='outside-after'){rect.fill='width';rect.edge='bottom';}}}
rect.className=this.disclosure.extend[rect.edge+'ClassName'];}
return rect;},_hideDisclosureComplete:function(){if(this._d.shown){this._d.shown=false;this.state.disclosure.shown=false;this._d.current.dEle.style.display='none';var dd=this.disclosures[this._d.current.s.name];if(dd){if(dd.onHide.constructor==Function)dd.onHide.call(this,this._d.current.dEle);}
if(this._d.next){this.showDisclosure(this._d.next,this._d.current.eleId);}else{this._d.ele.style.display='none';this._d.current=false;}
this.refresh();}},_refreshAnimComplete:function(){this._m.anim=false;if(this._m.next.has){this._m.next.has=false;this.refresh.apply(this,this._m.next.args);delete this._m.next.args;}},_resizeDis:function(){if(this._d.shown){var ci=this
clearTimeout(this._rdTO);this._rdTO=setTimeout(function(){ci.resizeDisclosure();delete ci},50);}},_disClick:function(e,ci){if(!ci._d.current.s.autoHide)return true;var cEle=$(ci.contId);var coor=$e.getCoors(e);var ele=document.elementFromPoint(coor.clientX,coor.clientY);if(!ele)return true;while(ele!=cEle&&ele!=document.body){if(ele==ci._d.current.dEle)return true;ele=ele.parentNode;}
ci.hideDisclosure();},_disCloseClick:function(e,ci){ci.hideDisclosure();},_click:function(e,ci){if(A5.u.drag._sDif>=$e.abstractEvents.click.scrollMax)return true;var id='';var r=ci._aEle(e);if(r&&ci._startItem){if(ci._startItem.i==r.i){if($ga(r.ele,'a5-disabled')!='true'&&!r.ele.disabled){id=r.ele.id;var iObj=ci.items[r.i];if(iObj){var dShown=ci._d.shown;if(iObj.disclosure){ci._d.internalShow=true;ci.showDisclosure(iObj.disclosure,r.ele);ci._d.internalShow=false;}
var iTObj=A5.controlBar.items[iObj.type];if(iTObj){if(iTObj.event)iTObj.event.call(ci,'click',r.i,r.v,iObj,r.ele,e);}
if(dShown&&!ci._d.next){if(iObj.autoHideDisclosure){var hide=false;if(iObj.autoHideDisclosure=='always')hide=true;else if(iObj.autoHideDisclosure!='never'&&ci._d.current.s.autoHide)hide=true;if(hide)ci.hideDisclosure();}}}}}}
if(this._oid==id)this._isdc=true;else{this._isdc=false;this._oid=id;}
delete r;},_dblClick:function(e,ci){if(!this._isdc)return false;var r=ci._aEle(e);if(r){if($ga(r.ele,'a5-disabled')!='true'&&!r.ele.disabled){var iObj=ci.items[r.i];if(iObj){var iTObj=A5.controlBar.items[iObj.type];if(iTObj){if(iTObj.event)iTObj.event.call(ci,'dblclick',r.i,r.v,iObj,r.ele,e);}}}}
delete r;},_rClick:function(e,ci){var r=ci._aEle(e);if(r){if($ga(r.ele,'a5-disabled')!='true'&&!r.ele.disabled){var iObj=ci.items[r.i];if(iObj){var iTObj=A5.controlBar.items[iObj.type];if(iTObj){if(iTObj.event)iTObj.event.call(ci,'contextclick',r.i,r.v,iObj,r.ele,e);}}}}
delete r;},_down:function(e,ci){var r=ci._aEle(e);ci._startItem=false;if(r){ci._startItem={i:r.i,v:r.v,id:r.ele.id};if($ga(r.ele,'a5-disabled')!='true'&&!r.ele.disabled){var iObj=ci.items[r.i];if(iObj){var iTObj=A5.controlBar.items[iObj.type];if(iTObj){if(iTObj.event)iTObj.event.call(ci,'down',r.i,r.v,iObj,r.ele,e);}}}}
delete r;},_up:function(e,ci){var r=ci._aEle(e);if(r){if($ga(r.ele,'a5-disabled')!='true'&&!r.ele.disabled){var iObj=ci.items[r.i];if(iObj){var iTObj=A5.controlBar.items[iObj.type];if(iTObj){if(iTObj.event)iTObj.event.call(ci,'up',r.i,r.v,iObj,r.ele,e);}}}}
delete r;},_downHold:function(e,ci){var r=ci._aEle(e);if(r){if($ga(r.ele,'a5-disabled')!='true'&&!r.ele.disabled){var iObj=ci.items[r.i];if(iObj){var iTObj=A5.controlBar.items[iObj.type];if(iTObj){if(iTObj.event)iTObj.event.call(ci,'downhold',r.i,r.v,iObj,r.ele,e);}}}}
delete r;},_swipe:function(e,ci){if(ci._startItem){var r=ci._startItem;var ele=$(r.id);if($ga(ele,'a5-disabled')!='true'&&!ele.disabled){var iObj=ci.items[r.i];if(iObj){var iTObj=A5.controlBar.items[iObj.type];if(iTObj){if(iTObj.event)iTObj.event.call(ci,'swipe',r.i,r.v,iObj,r.ele,e);}}}}},_aEle:function(e){var cEle=$(this.contId);var coor=$e.getCoors(e);var ele=document.elementFromPoint(coor.clientX,coor.clientY);if(!ele)return false;var i='';while(ele!=cEle&&ele!=document.body){i=$ga(ele,'a5-item');if(i!=null&&i!=''){var v=this._getValue(ele);return{i:i,v:v,ele:ele};}
ele=ele.parentNode;}
return false;},_getValue:function(ele){var v=$ga(ele,'a5-value');if(v==''||v==null)v=ele.id;return v;},_bindEvents:function(ele){var egName='CONTROLBAR.'+this.contId;$e.add(ele,A5.d.evnts.click,this._click,this,false,egName);$e.add(ele,A5.d.evnts.dblClick,this._dblClick,this,false,egName);$e.add(ele,'contextmenu',this._rClick,this,false,egName);$e.add(ele,A5.d.evnts.down,this._down,this,false,egName);$e.add(ele,A5.d.evnts.up,this._up,this,false,egName);$e.add(ele,'abstractdownhold',this._downHold,this,false,egName);$e.add(ele,'abstractswipe',this._swipe,this,false,egName);},_compileTemplate:function(cl,edge){if(typeof cl._t=='undefined')cl._t={};if(typeof cl._t[edge]=='undefined'){var tLines=[];var l=null;var ti=null;var cn='';var temp=[];var name='';for(var i=0;i<cl.lines.length;i++){l=cl.lines[i];$u.o.assign(l,A5.controlBar._.lDefs,true);cn='A5ControlBarLine';if(l.middle.items.length==0){if(l.before.items.length==0)cn='A5ControlBarLine A5ControlBarLineAfter';else cn='A5ControlBarLine A5ControlBarLineBefore';}
temp=['<div class="'+cn+' '+l.className+'">'];if(l.before.items.length!=0){temp.push('<div class="A5ControlBarLineContentBefore">');for(var k=0;k<l.before.items.length;k++){name=l.before.items[k];if(name=='-'){temp.push('<div class="A5ControlBarItem A5CONTROLBARSEPCLASSNAME">&nbsp;</div>');}else if(name[0]=='<'){name=name.substring(1,name.length-1).trim();temp.push('<div class="A5ControlBarItem" style="A5CONTROLBARITEMSIZE: '+name+';"></div>');}else if(this.items[name])temp.push(this.items[name].template);}
temp.push('</div>');}
if(l.middle.items.length!=0){temp.push('<div class="A5ControlBarLineContentMiddle">');for(var k=0;k<l.middle.items.length;k++){name=l.middle.items[k];if(name=='-'){temp.push('<div class="A5ControlBarItem A5CONTROLBARSEPCLASSNAME">&nbsp;</div>');}else if(name[0]=='<'){name=name.substring(1,name.length-1).trim();temp.push('<div class="A5ControlBarItem" style="A5CONTROLBARITEMSIZE: '+name+';"></div>');}else if(this.items[name])temp.push(this.items[name].template);}
temp.push('</div>');}
if(l.after.items.length!=0){temp.push('<div class="A5ControlBarLineContentAfter">');for(var k=0;k<l.after.items.length;k++){name=l.after.items[k];if(name=='-'){temp.push('<div class="A5ControlBarItem A5CONTROLBARSEPCLASSNAME">&nbsp;</div>');}else if(name[0]=='<'){name=name.substring(1,name.length-1).trim();temp.push('<div class="A5ControlBarItem" style="A5CONTROLBARITEMSIZE: '+name+';"></div>');}else if(this.items[name])temp.push(this.items[name].template);}
temp.push('</div>');}
temp.push('</div>');tLines.push(temp.join(''));}
if(edge=='left'){tLines.unshift('<div class="A5ControlBarVert">');tLines.push('</div>');}else if(edge=='bottom'){tLines.reverse();tLines.unshift('<div class="A5ControlBarHorz">');tLines.push('</div>');}else if(edge=='right'){tLines.reverse();tLines.unshift('<div class="A5ControlBarVert">');tLines.push('</div>');}else{tLines.unshift('<div class="A5ControlBarHorz">');tLines.push('</div>');}
tLines=tLines.join('');if(edge=='left'||edge=='right'){tLines=tLines.replace(/A5CONTROLBARITEMSIZE/gi,'height');tLines=tLines.replace(/A5CONTROLBARSEPCLASSNAME/gi,this.separator.verticalClassName);}else{tLines=tLines.replace(/A5CONTROLBARITEMSIZE/gi,'width');tLines=tLines.replace(/A5CONTROLBARSEPCLASSNAME/gi,this.separator.horizontalClassName);}
cl._t[edge]=A5.u.template.parse(tLines);}}});