/*
@license

dhtmlxGantt v.4.1.0 Professional
This software is covered by DHTMLX Enterprise License. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Gantt.plugin(function(t){t._formatLink=function(e){var i=[],n=this._get_link_target(e),a=this._get_link_source(e);if(!a||!n)return i;if(t.isChildOf(a.id,n.id)&&t._isProject(n)||t.isChildOf(n.id,a.id)&&t._isProject(a))return i;for(var s=this._getImplicitLinks(e,a,function(t){return 0}),r=t.config.auto_scheduling_move_projects,o=this._isProject(n)?this.getSubtaskDates(n.id):{start_date:n.start_date,end_date:n.end_date},_=this._getImplicitLinks(e,n,function(e){return r?e.$target.length?0:t.calculateDuration(t.roundDate(o.start_date),t.roundDate(e.start_date)):0;
}),l=0;l<s.length;l++)for(var d=s[l],c=0;c<_.length;c++){var h=_[c],u=d.lag+h.lag,g=t.copy(e);g.source=d.task,g.target=h.task,g.lag=(g.lag||0)+u,i.push(t._convertToFinishToStartLink(h.task,g,a,n))}return i},t._getImplicitLinks=function(t,e,i){var n=[];return this._isProject(e)?this.eachTask(function(t){this._isProject(t)||n.push({task:t.id,lag:i(t)})},e.id):n.push({task:e.id,lag:0}),n},t._getDirectDependencies=function(t,e){for(var i=[],n=[],a=e?t.$source:t.$target,s=0;s<a.length;s++){var r=this.getLink(a[s]);
this.isTaskExists(r.source)&&this.isTaskExists(r.target)&&i.push(this.getLink(a[s]))}for(var s=0;s<i.length;s++)n=n.concat(this._formatLink(i[s]));return n},t._getInheritedDependencies=function(t,e){var i=[],n=[];if(this.isTaskExists(t.id)){this._eachParent(function(t){this._isProject(t)&&n.push.apply(n,this._getDirectDependencies(t,e))},t.id,this);for(var a=0;a<n.length;a++){var s=e?n[a].source:n[a].target;s==t.id&&i.push(n[a])}}return i},t._getDirectSuccessors=function(t){return this._getDirectDependencies(t,!0);
},t._getInheritedSuccessors=function(t){return this._getInheritedDependencies(t,!0)},t._getDirectPredecessors=function(t){return this._getDirectDependencies(t,!1)},t._getInheritedPredecessors=function(t){return this._getInheritedDependencies(t,!1)},t._getSuccessors=function(t){return this._getDirectSuccessors(t).concat(this._getInheritedSuccessors(t))},t._getPredecessors=function(t){return this._getDirectPredecessors(t).concat(this._getInheritedPredecessors(t))},t._convertToFinishToStartLink=function(e,i,n,a){
var s={target:e,link:t.config.links.finish_to_start,id:i.id,lag:i.lag||0,source:i.source,preferredStart:null},r=0;switch(i.type){case t.config.links.start_to_start:r=-n.duration;break;case t.config.links.finish_to_finish:r=-a.duration;break;case t.config.links.start_to_finish:r=-n.duration-a.duration;break;default:r=0}return s.lag+=r,s},t.config.highlight_critical_path=!1,t._criticalPathHandler=function(){t.config.highlight_critical_path&&t.render()},t.attachEvent("onAfterLinkAdd",t._criticalPathHandler),
t.attachEvent("onAfterLinkUpdate",t._criticalPathHandler),t.attachEvent("onAfterLinkDelete",t._criticalPathHandler),t.attachEvent("onAfterTaskAdd",t._criticalPathHandler),t.attachEvent("onAfterTaskUpdate",t._criticalPathHandler),t.attachEvent("onAfterTaskDelete",t._criticalPathHandler),t.isCriticalTask=function(e){if(t.assert(!(!e||void 0===e.id),"Invalid argument for gantt.isCriticalTask"),e&&e.id){var i=arguments[1]||{};if(this._isProjectEnd(e))return!0;i[e.id]=!0;for(var n=this._getDependencies(e),a=0;a<n.length;a++){
var s=this.getTask(n[a].target);if(this._getSlack(e,s,n[a])<=0&&!i[s.id]&&this.isCriticalTask(s,i))return!0}return!1}},t.isCriticalLink=function(e){return this.isCriticalTask(t.getTask(e.source))},t.getSlack=function(t,e){for(var i=[],n={},a=0;a<t.$source.length;a++)n[t.$source[a]]=!0;for(var a=0;a<e.$target.length;a++)n[e.$target[a]]&&i.push(e.$target[a]);for(var s=[],a=0;a<i.length;a++){var r=this.getLink(i[a]);s.push(this._getSlack(t,e,this._convertToFinishToStartLink(r.id,r,t,e)))}return Math.min.apply(Math,s);
},t._getSlack=function(t,e,i){var n=this.config.types,a=null;a=this._get_safe_type(t.type)==n.milestone?t.start_date:t.end_date;var s=e.start_date,r=0;r=+a>+s?-this.calculateDuration(s,a):this.calculateDuration(a,s);var o=i.lag;return o&&1*o==o&&(r-=o),r},t._getProjectEnd=function(){var e=t.getTaskByTime();return e=e.sort(function(t,e){return+t.end_date>+e.end_date?1:-1}),e.length?e[e.length-1].end_date:null},t._isProjectEnd=function(t){return!this._hasDuration(t.end_date,this._getProjectEnd())},
t._getSummaryPredecessors=function(e){var i=[];return this._eachParent(function(e){this._isProject(e)&&(i=i.concat(t._getDependencies(e)))},e),i},t._getDependencies=function(t){var e=this._getSuccessors(t).concat(this._getSummaryPredecessors(t));return e}});
//# sourceMappingURL=../sources/ext/dhtmlxgantt_critical_path.js.map