/*
@license

dhtmlxGantt v.4.2.1 Professional
This software is covered by DHTMLX Enterprise License. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Gantt.plugin(function(t){t._formatLink=function(e){var i=[],n=this._get_link_target(e),a=this._get_link_source(e);if(!a||!n)return i;if(t.isChildOf(a.id,n.id)&&t._isProject(n)||t.isChildOf(n.id,a.id)&&t._isProject(a))return i;for(var r=this._getImplicitLinks(e,a,function(t){return 0}),s=t.config.auto_scheduling_move_projects,o=this._isProject(n)?this.getSubtaskDates(n.id):{start_date:n.start_date,end_date:n.end_date},_=this._getImplicitLinks(e,n,function(e){return s?e.$target.length||t.getState().drag_id==e.id?0:t.calculateDuration({
start_date:o.start_date,end_date:e.start_date,task:a}):0}),l=0;l<r.length;l++)for(var d=r[l],c=0;c<_.length;c++){var h=_[c],u=1*d.lag+1*h.lag,g={id:e.id,type:e.type,source:d.task,target:h.task,lag:(1*e.lag||0)+u};i.push(t._convertToFinishToStartLink(h.task,g,a,n))}return i},t._getImplicitLinks=function(t,e,i){var n=[];return this._isProject(e)?this.eachTask(function(t){this._isProject(t)||n.push({task:t.id,lag:i(t)})},e.id):n.push({task:e.id,lag:0}),n},t._getDirectDependencies=function(t,e){for(var i=[],n=[],a=e?t.$source:t.$target,r=0;r<a.length;r++){
var s=this.getLink(a[r]);this.isTaskExists(s.source)&&this.isTaskExists(s.target)&&i.push(this.getLink(a[r]))}for(var r=0;r<i.length;r++)n=n.concat(this._formatLink(i[r]));return n},t._getInheritedDependencies=function(t,e){var i=[],n=[];if(this.isTaskExists(t.id)){this._eachParent(function(t){this._isProject(t)&&n.push.apply(n,this._getDirectDependencies(t,e))},t.id,this);for(var a=0;a<n.length;a++){var r=e?n[a].source:n[a].target;r==t.id&&i.push(n[a])}}return i},t._getDirectSuccessors=function(t){
return this._getDirectDependencies(t,!0)},t._getInheritedSuccessors=function(t){return this._getInheritedDependencies(t,!0)},t._getDirectPredecessors=function(t){return this._getDirectDependencies(t,!1)},t._getInheritedPredecessors=function(t){return this._getInheritedDependencies(t,!1)},t._getSuccessors=function(t){return this._getDirectSuccessors(t).concat(this._getInheritedSuccessors(t))},t._getPredecessors=function(t){return this._getDirectPredecessors(t).concat(this._getInheritedPredecessors(t));
},t._convertToFinishToStartLink=function(e,i,n,a){var r={target:e,link:t.config.links.finish_to_start,id:i.id,lag:i.lag||0,source:i.source,preferredStart:null},s=0;switch(i.type){case t.config.links.start_to_start:s=-n.duration;break;case t.config.links.finish_to_finish:s=-a.duration;break;case t.config.links.start_to_finish:s=-n.duration-a.duration;break;default:s=0}return r.lag+=s,r},t.config.highlight_critical_path=!1,t._criticalPathHandler=function(){t.config.highlight_critical_path&&t.render();
},t.attachEvent("onAfterLinkAdd",t._criticalPathHandler),t.attachEvent("onAfterLinkUpdate",t._criticalPathHandler),t.attachEvent("onAfterLinkDelete",t._criticalPathHandler),t.attachEvent("onAfterTaskAdd",t._criticalPathHandler),t.attachEvent("onAfterTaskUpdate",t._criticalPathHandler),t.attachEvent("onAfterTaskDelete",t._criticalPathHandler),t._isCriticalTask=function(t,e){if(t&&t.id){var i=e||{};if(this._isProjectEnd(t))return!0;i[t.id]=!0;for(var n=this._getDependencies(t),a=0;a<n.length;a++){var r=this.getTask(n[a].target);
if(this._getSlack(t,r,n[a])<=0&&!i[r.id]&&this._isCriticalTask(r,i))return!0}return!1}},t.isCriticalTask=function(e){return t.assert(!(!e||void 0===e.id),"Invalid argument for gantt.isCriticalTask"),this._isCriticalTask(e,{})},t.isCriticalLink=function(e){return this.isCriticalTask(t.getTask(e.source))},t.getSlack=function(t,e){for(var i=[],n={},a=0;a<t.$source.length;a++)n[t.$source[a]]=!0;for(var a=0;a<e.$target.length;a++)n[e.$target[a]]&&i.push(e.$target[a]);for(var r=[],a=0;a<i.length;a++){var s=this.getLink(i[a]);
r.push(this._getSlack(t,e,this._convertToFinishToStartLink(s.id,s,t,e)))}return Math.min.apply(Math,r)},t._getSlack=function(t,e,i){var n=this.config.types,a=null;a=this._get_safe_type(t.type)==n.milestone?t.start_date:t.end_date;var r=e.start_date,s=0;s=+a>+r?-this.calculateDuration({start_date:r,end_date:a,task:t}):this.calculateDuration({start_date:a,end_date:r,task:t});var o=i.lag;return o&&1*o==o&&(s-=o),s},t._getProjectEnd=function(){var e=t.getTaskByTime();return e=e.sort(function(t,e){return+t.end_date>+e.end_date?1:-1;
}),e.length?e[e.length-1].end_date:null},t._isProjectEnd=function(t){return!this._hasDuration({start_date:t.end_date,end_date:this._getProjectEnd(),task:t})},t._getSummaryPredecessors=function(e){var i=[];return this._eachParent(function(e){this._isProject(e)&&(i=i.concat(t._getDependencies(e)))},e),i},t._getDependencies=function(t){var e=this._getSuccessors(t).concat(this._getSummaryPredecessors(t));return e}});
//# sourceMappingURL=../sources/ext/dhtmlxgantt_critical_path.js.map