/*
@license

dhtmlxGantt v.4.2.1 Professional
This software is covered by DHTMLX Enterprise License. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Gantt.plugin(function(t){t._formatLink=function(e){var i=[],n=this._get_link_target(e),a=this._get_link_source(e);if(!a||!n)return i;if(t.isChildOf(a.id,n.id)&&t._isProject(n)||t.isChildOf(n.id,a.id)&&t._isProject(a))return i;for(var r=this._getImplicitLinks(e,a,function(t){return 0}),s=t.config.auto_scheduling_move_projects,o=this._isProject(n)?this.getSubtaskDates(n.id):{start_date:n.start_date,end_date:n.end_date},l=this._getImplicitLinks(e,n,function(e){return s?e.$target.length||t.getState().drag_id==e.id?0:t.calculateDuration({
start_date:o.start_date,end_date:e.start_date,task:a}):0}),_=0;_<r.length;_++)for(var d=r[_],c=0;c<l.length;c++){var h=l[c],u=1*d.lag+1*h.lag,g={id:e.id,type:e.type,source:d.task,target:h.task,lag:(1*e.lag||0)+u};i.push(t._convertToFinishToStartLink(h.task,g,a,n))}return i},t._getImplicitLinks=function(t,e,i){var n=[];return this._isProject(e)?this.eachTask(function(t){this._isProject(t)||n.push({task:t.id,lag:i(t)})},e.id):n.push({task:e.id,lag:0}),n},t._getDirectDependencies=function(t,e){for(var i=[],n=[],a=e?t.$source:t.$target,r=0;r<a.length;r++){
var s=this.getLink(a[r]);this.isTaskExists(s.source)&&this.isTaskExists(s.target)&&i.push(this.getLink(a[r]))}for(var r=0;r<i.length;r++)n=n.concat(this._formatLink(i[r]));return n},t._getInheritedDependencies=function(t,e){var i=[],n=[];if(this.isTaskExists(t.id)){this._eachParent(function(t){this._isProject(t)&&n.push.apply(n,this._getDirectDependencies(t,e))},t.id,this);for(var a=0;a<n.length;a++){var r=e?n[a].source:n[a].target;r==t.id&&i.push(n[a])}}return i},t._getDirectSuccessors=function(t){
return this._getDirectDependencies(t,!0)},t._getInheritedSuccessors=function(t){return this._getInheritedDependencies(t,!0)},t._getDirectPredecessors=function(t){return this._getDirectDependencies(t,!1)},t._getInheritedPredecessors=function(t){return this._getInheritedDependencies(t,!1)},t._getSuccessors=function(t){return this._getDirectSuccessors(t).concat(this._getInheritedSuccessors(t))},t._getPredecessors=function(t){return this._getDirectPredecessors(t).concat(this._getInheritedPredecessors(t));
},t._convertToFinishToStartLink=function(e,i,n,a){var r={target:e,link:t.config.links.finish_to_start,id:i.id,lag:i.lag||0,source:i.source,preferredStart:null},s=0;switch(i.type){case t.config.links.start_to_start:s=-n.duration;break;case t.config.links.finish_to_finish:s=-a.duration;break;case t.config.links.start_to_finish:s=-n.duration-a.duration;break;default:s=0}return r.lag+=s,r},t.config.auto_scheduling=!1,t.config.auto_scheduling_descendant_links=!1,t.config.auto_scheduling_initial=!0,t.config.auto_scheduling_strict=!1,
t.config.auto_scheduling_move_projects=!0,t._forEach=function(t,e){for(var i=t.slice(),n=0;n<i.length;n++)e(i[n],n)},t._arrayMap=function(t,e){for(var i=t.slice(),n=[],a=0;a<i.length;a++)n.push(e(i[a],a));return n},t._autoSchedulingGraph={getVertices:function(e){var i={};t._forEach(e,function(t){i[t.target]=t.target,i[t.source]=t.source});var n=[];for(var a in i)n.push(i[a]);return n.sort(function(e,i){return t.getGlobalTaskIndex(e)-t.getGlobalTaskIndex(i)})},topologicalSort:function(t){for(var e=this.getVertices(t),i={},n=0;n<e.length;n++)i[e[n]]={
id:e[n],$source:[],$target:[],$incoming:0};for(var n=0;n<t.length;n++){var a=i[t[n].target];a.$target.push(n),a.$incoming=a.$target.length,i[t[n].source].$source.push(n)}for(var r=e.filter(function(t){return!i[t].$incoming}),s=[];r.length;){var o=r.pop();s.push(o);for(var l=i[o],n=0;n<l.$source.length;n++){var _=i[t[l.$source[n]].target];_.$incoming--,_.$incoming||r.push(_.id)}}return s},tarjanStronglyConnectedComponents:function(e,i){function n(e,r){var d=a(e);if(d.index=s,d.lowLink=s,s++,r&&l.push(r),
o.push(d),d.onStack=!0,t._forEach(i,function(t){if(t.source==e){var i=a(t.source),r=a(t.target);void 0===r.index?(n(t.target,t),i.lowLink=Math.min(i.lowLink,r.lowLink)):r.onStack&&(i.lowLink=Math.min(i.lowLink,r.index),l.push(t))}}),d.lowLink==d.index){var c,h={tasks:[],links:[]};do{var u=l.pop();c=o.pop(),c.onStack=!1,h.tasks.push(c.id),u&&h.links.push(u.id)}while(c.id!=d.id);_.push(h)}}function a(t){return r[t]||(r[t]={id:t}),r[t]}var r={},s=0,o=[],l=[],_=[];return t._forEach(e,function(t){var e=a(t);
void 0===e.index&&n(t)}),_}},t._autoSchedulingPath={getKey:function(t){return[t.lag,t.link,t.source,t.target].join("_")},getVirtualRoot:function(){return t.mixin(t.getSubtaskDates(),{id:t.config.root_id,type:t.config.types.project,$source:[],$target:[],$virtual:!0})},filterDuplicates:function(t){for(var e={},i=0;i<t.length;i++){var n=this.getKey(t[i]);e[n]?(t.splice(i,1),i--):e[n]=!0}return t},getLinkedTasks:function(t,e){for(var i=[t],n=[],a={},r=0;r<i.length;r++)n=n.concat(this._getLinkedTasks(i[r],a,e));
return n},_getLinkedTasks:function(e,i,n){var a=void 0===e?t.config.root_id:e,r=i||{},s=t.isTaskExists(a)?t.getTask(a):this.getVirtualRoot(),o=t._getSuccessors(s);n&&o.push.apply(o,t._getPredecessors(s));for(var l=[],_=0;_<o.length;_++)r[this.getKey(o[_])]||(r[this.getKey(o[_])]=!0,l=l.concat(this._getLinkedTasks(o[_].target,r,!0)));for(var d=t.getChildren(s.id),_=0;_<d.length;_++)o=o.concat(this._getLinkedTasks(d[_],r,!0));return this.filterDuplicates(o.concat(l))},findLoops:function(e){var i=[];
t._forEach(e,function(t){t.target==t.source&&i.push([t.target,t.source])});var n=t._autoSchedulingGraph,a=n.getVertices(e),r=n.tarjanStronglyConnectedComponents(a,e);return t._forEach(r,function(t){t.tasks.length>1&&i.push(t)}),i}},t._autoSchedulingDateResolver={isFirstSmaller:function(e,i,n){return e.valueOf()<i.valueOf()&&t._hasDuration(e,i,n)?!0:!1},isSmallerOrDefault:function(t,e,i){return!(t&&!this.isFirstSmaller(t,e,i))},resolveRelationDate:function(e,i,n){for(var a=null,r=null,s=null,o=0;o<i.length;o++){
var l=i[o];e=l.target,s=l.preferredStart;var _=this.getConstraintDate(l,n);this.isSmallerOrDefault(s,_,t.getTask(e))&&this.isSmallerOrDefault(a,_,t.getTask(e))&&(a=_,r=l.id)}return a&&(a=t.getClosestWorkTime({date:a,dir:"future",task:t.getTask(e)})),{link:r,task:e,start_date:a}},getConstraintDate:function(e,i){var n=i(e.source);return n&&e.lag&&1*e.lag==e.lag&&(n=t.calculateEndDate({start_date:n,duration:1*e.lag,task:t.getTask(e.source)})),n}},t._autoSchedulingPlanner={generatePlan:function(e){function i(e){
var i=s[e],n=t.getTask(e);return i&&(i.start_date||i.end_date)?i.end_date?i.end_date:t.calculateEndDate({start_date:i.start_date,duration:n.duration,task:n}):t.getClosestWorkTime({date:n.end_date,dir:"future",task:n})}var n=t._autoSchedulingGraph,a=n.topologicalSort(e),r={},s={};t._arrayMap(a,function(e){var i=t.getTask(e);i.auto_scheduling!==!1&&(r[e]=[],s[e]=null)});for(var o=0;o<e.length;o++)r[e[o].target]&&r[e[o].target].push(e[o]);for(var l=t._autoSchedulingDateResolver,_=[],o=0;o<a.length;o++){
var d=a[o],c=l.resolveRelationDate(d,r[d]||[],i);if(c.start_date&&t.isLinkExists(c.link)){var h=t.getLink(c.link),u=t.getTask(d),g=t.getTask(h.source);if(u.start_date.valueOf()!==c.start_date.valueOf()&&t.callEvent("onBeforeTaskAutoSchedule",[u,c.start_date,h,g])===!1)continue}s[d]=c,c.start_date&&_.push(c)}return _},applyProjectPlan:function(e){for(var i,n,a,r,s=[],o=0;o<e.length;o++)if(a=null,r=null,i=e[o],i.task){n=t.getTask(i.task),i.link&&(a=t.getLink(i.link),r=t.getTask(a.source));var l=null;
i.start_date&&n.start_date.valueOf()!=i.start_date.valueOf()&&(l=i.start_date),l&&(n.start_date=l,n.end_date=t.calculateEndDate(n),s.push(n.id),t.callEvent("onAfterTaskAutoSchedule",[n,l,a,r]))}return s}},t._autoSchedulingPreferredDates=function(e,i){for(var n=0;n<i.length;n++){var a=i[n],r=t.getTask(a.target);t.config.auto_scheduling_strict&&a.target!=e||(a.preferredStart=new Date(r.start_date))}},t._autoSchedule=function(e,i,n){if(t.callEvent("onBeforeAutoSchedule",[e])!==!1){t._autoscheduling_in_progress=!0;
var a=t._autoSchedulingPath,r=[],s=a.findLoops(i);if(s.length)t.callEvent("onAutoScheduleCircularLink",[s]);else{var o=t._autoSchedulingPlanner;t._autoSchedulingPreferredDates(e,i);var l=o.generatePlan(i);r=o.applyProjectPlan(l),n&&n(r)}return t._autoscheduling_in_progress=!1,t.callEvent("onAfterAutoSchedule",[e,r]),r}},t.autoSchedule=function(e,i){i=void 0===i?!0:!!i;var n=t._autoSchedulingPath.getLinkedTasks(e,i);t._autoSchedule(e,n,t._finalizeAutoSchedulingChanges)},t._finalizeAutoSchedulingChanges=function(e){
function i(e){if(!a){var n=e.start_date.valueOf(),r=e.end_date.valueOf();if(t.resetProjectDates(e),e.start_date.valueOf()!=n||e.end_date.valueOf()!=r)return void(a=!0);for(var s=t.getChildren(e.id),o=0;!a&&o<s.length;o++)i(t.getTask(s[o]))}}function n(){for(var i=0;i<e.length;i++)t.updateTask(e[i])}var a=!1;1==e.length?t._eachParent(i,e[0]):e.length&&(a=!0),a?t.batchUpdate(n):n()},t.isCircularLink=function(e){return!!t._getConnectedGroup(e)},t._getConnectedGroup=function(e){var i=t._autoSchedulingPath,n=i.getLinkedTasks();
t.isLinkExists(e.id)||(n=n.concat(t._formatLink(e)));for(var a=i.findLoops(n),r=!1,s=0;s<a.length&&!r;s++)for(var o=a[s].links,l=0;l<o.length;l++)if(o[l]==e.id)return a[s];return null},t.findCycles=function(){var e=t._autoSchedulingPath,i=e.getLinkedTasks();return e.findLoops(i)},t._attachAutoSchedulingHandlers=function(){function e(e,i){for(var n=!1,a=0;a<i.length;a++){var r=t.getLink(i[a].id);(r.type==t.config.links.start_to_start||r.type==t.config.links.start_to_finish)&&(i.splice(a,1),a--,n=!0);
}if(n){for(var s={},a=0;a<i.length;a++)s[i[a].id]=!0;for(var o=t._autoSchedulingPath.getLinkedTasks(e,!0),a=0;a<o.length;a++)s[o[a].id]||i.push(o[a])}}t._autoScheduleAfterLinkChange=function(e,i){t.config.auto_scheduling&&!this._autoscheduling_in_progress&&t.autoSchedule(i.source)},t.attachEvent("onAfterLinkUpdate",t._autoScheduleAfterLinkChange),t.attachEvent("onAfterLinkAdd",t._autoScheduleAfterLinkChange),t.attachEvent("onParse",function(){t.config.auto_scheduling&&t.config.auto_scheduling_initial&&t.autoSchedule();
}),t._preventCircularLink=function(e,i){return t.isCircularLink(i)?(t.callEvent("onCircularLinkError",[i,t._getConnectedGroup(i)]),!1):!0},t._preventDescendantLink=function(e,i){var n=t.getTask(i.source),a=t.getTask(i.target);return!t.config.auto_scheduling_descendant_links&&(t.isChildOf(n.id,a.id)&&t._isProject(a)||t.isChildOf(a.id,n.id)&&t._isProject(n))?!1:!0},t.attachEvent("onBeforeLinkAdd",t._preventCircularLink),t.attachEvent("onBeforeLinkAdd",t._preventDescendantLink),t.attachEvent("onBeforeLinkUpdate",t._preventCircularLink),
t.attachEvent("onBeforeLinkUpdate",t._preventDescendantLink),t._datesNotEqual=function(t,e,i,n){return t.valueOf()>e.valueOf()?this._hasDuration({start_date:e,end_date:t,task:n}):this._hasDuration({start_date:t,end_date:e,task:i})},t._notEqualTaskDates=function(e,i){return this._datesNotEqual(e.start_date,i.start_date,e,i)||(this._datesNotEqual(e.end_date,i.end_date,e,i)||e.duration!=i.duration)&&e.type!=t.config.types.milestone?!0:void 0};var i,n;t.attachEvent("onBeforeTaskDrag",function(e,a,r){
return t.config.auto_scheduling_move_projects&&(i=t._autoSchedulingPath.getLinkedTasks(e,!0),n=e),!0}),t._autoScheduleAfterDND=function(a,r){if(t.config.auto_scheduling&&!this._autoscheduling_in_progress){var s=this.getTask(a);t._notEqualTaskDates(r,s)&&(t.config.auto_scheduling_move_projects&&n==a?(t.calculateDuration(r)!=t.calculateDuration(s)&&e(a,i),t._autoSchedule(a,i,t._finalizeAutoSchedulingChanges)):t.autoSchedule(s.id))}return i=null,n=null,!0},t._lightBoxChangesHandler=function(e,i){if(t.config.auto_scheduling&&!this._autoscheduling_in_progress){
var n=this.getTask(e);t._notEqualTaskDates(i,n)&&(t._autoschedule_lightbox_id=e)}return!0},t._lightBoxSaveHandler=function(e,i){return t.config.auto_scheduling&&!this._autoscheduling_in_progress&&t._autoschedule_lightbox_id&&t._autoschedule_lightbox_id==e&&(t._autoschedule_lightbox_id=null,t.autoSchedule(i.id)),!0},t.attachEvent("onBeforeTaskChanged",function(e,i,n){return t._autoScheduleAfterDND(e,n)}),t.attachEvent("onLightboxSave",t._lightBoxChangesHandler),t.attachEvent("onAfterTaskUpdate",t._lightBoxSaveHandler);
},t.attachEvent("onGanttReady",function(){t._attachAutoSchedulingHandlers()})});
//# sourceMappingURL=../sources/ext/dhtmlxgantt_auto_scheduling.js.map