/*
@license

dhtmlxGantt v.4.1.22 Professional
This software is covered by DHTMLX Enterprise License. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Gantt.plugin(function(t){t._formatLink=function(e){var i=[],n=this._get_link_target(e),a=this._get_link_source(e);if(!a||!n)return i;if(t.isChildOf(a.id,n.id)&&t._isProject(n)||t.isChildOf(n.id,a.id)&&t._isProject(a))return i;for(var r=this._getImplicitLinks(e,a,function(t){return 0}),s=t.config.auto_scheduling_move_projects,o=this._isProject(n)?this.getSubtaskDates(n.id):{start_date:n.start_date,end_date:n.end_date},_=this._getImplicitLinks(e,n,function(e){return s?e.$target.length||t.getState().drag_id==e.id?0:t.calculateDuration(o.start_date,e.start_date):0;
}),l=0;l<r.length;l++)for(var d=r[l],h=0;h<_.length;h++){var c=_[h],u=1*d.lag+1*c.lag,g={id:e.id,type:e.type,source:d.task,target:c.task,lag:(1*e.lag||0)+u};i.push(t._convertToFinishToStartLink(c.task,g,a,n))}return i},t._getImplicitLinks=function(t,e,i){var n=[];return this._isProject(e)?this.eachTask(function(t){this._isProject(t)||n.push({task:t.id,lag:i(t)})},e.id):n.push({task:e.id,lag:0}),n},t._getDirectDependencies=function(t,e){for(var i=[],n=[],a=e?t.$source:t.$target,r=0;r<a.length;r++){
var s=this.getLink(a[r]);this.isTaskExists(s.source)&&this.isTaskExists(s.target)&&i.push(this.getLink(a[r]))}for(var r=0;r<i.length;r++)n=n.concat(this._formatLink(i[r]));return n},t._getInheritedDependencies=function(t,e){var i=[],n=[];if(this.isTaskExists(t.id)){this._eachParent(function(t){this._isProject(t)&&n.push.apply(n,this._getDirectDependencies(t,e))},t.id,this);for(var a=0;a<n.length;a++){var r=e?n[a].source:n[a].target;r==t.id&&i.push(n[a])}}return i},t._getDirectSuccessors=function(t){
return this._getDirectDependencies(t,!0)},t._getInheritedSuccessors=function(t){return this._getInheritedDependencies(t,!0)},t._getDirectPredecessors=function(t){return this._getDirectDependencies(t,!1)},t._getInheritedPredecessors=function(t){return this._getInheritedDependencies(t,!1)},t._getSuccessors=function(t){return this._getDirectSuccessors(t).concat(this._getInheritedSuccessors(t))},t._getPredecessors=function(t){return this._getDirectPredecessors(t).concat(this._getInheritedPredecessors(t));
},t._convertToFinishToStartLink=function(e,i,n,a){var r={target:e,link:t.config.links.finish_to_start,id:i.id,lag:i.lag||0,source:i.source,preferredStart:null},s=0;switch(i.type){case t.config.links.start_to_start:s=-n.duration;break;case t.config.links.finish_to_finish:s=-a.duration;break;case t.config.links.start_to_finish:s=-n.duration-a.duration;break;default:s=0}return r.lag+=s,r},t.config.auto_scheduling=!1,t.config.auto_scheduling_descendant_links=!1,t.config.auto_scheduling_initial=!0,t.config.auto_scheduling_strict=!1,
t.config.auto_scheduling_move_projects=!0,t._forEach=function(t,e){for(var i=t.slice(),n=0;n<i.length;n++)e(i[n],n)},t._arrayMap=function(t,e){for(var i=t.slice(),n=[],a=0;a<i.length;a++)n.push(e(i[a],a));return n},t._autoSchedulingGraph={getVertices:function(e){var i={};t._forEach(e,function(t){i[t.target]=t.target,i[t.source]=t.source});var n=[];for(var a in i)n.push(i[a]);return n.sort(function(e,i){return t.getGlobalTaskIndex(e)-t.getGlobalTaskIndex(i)})},topologicalSort:function(t){for(var e=this.getVertices(t),i={},n=0;n<e.length;n++)i[e[n]]={
id:e[n],$source:[],$target:[],$incoming:0};for(var n=0;n<t.length;n++){var a=i[t[n].target];a.$target.push(n),a.$incoming=a.$target.length,i[t[n].source].$source.push(n)}for(var r=e.filter(function(t){return!i[t].$incoming}),s=[];r.length;){var o=r.pop();s.push(o);for(var _=i[o],n=0;n<_.$source.length;n++){var l=i[t[_.$source[n]].target];l.$incoming--,l.$incoming||r.push(l.id)}}return s},tarjanStronglyConnectedComponents:function(e,i){function n(e,r){var d=a(e);if(d.index=s,d.lowLink=s,s++,r&&_.push(r),
o.push(d),d.onStack=!0,t._forEach(i,function(t){if(t.source==e){var i=a(t.source),r=a(t.target);void 0===r.index?(n(t.target,t),i.lowLink=Math.min(i.lowLink,r.lowLink)):r.onStack&&(i.lowLink=Math.min(i.lowLink,r.index),_.push(t))}}),d.lowLink==d.index){var h,c={tasks:[],links:[]};do{var u=_.pop();h=o.pop(),h.onStack=!1,c.tasks.push(h.id),u&&c.links.push(u.id)}while(h.id!=d.id);l.push(c)}}function a(t){return r[t]||(r[t]={id:t}),r[t]}var r={},s=0,o=[],_=[],l=[];return t._forEach(e,function(t){var e=a(t);
void 0===e.index&&n(t)}),l}},t._autoSchedulingPath={getKey:function(t){return[t.lag,t.link,t.source,t.target].join("_")},getVirtualRoot:function(){return t.mixin(t.getSubtaskDates(),{id:t.config.root_id,type:t.config.types.project,$source:[],$target:[],$virtual:!0})},filterDuplicates:function(t){for(var e={},i=0;i<t.length;i++){var n=this.getKey(t[i]);e[n]?(t.splice(i,1),i--):e[n]=!0}return t},getLinkedTasks:function(t,e){for(var i=[t],n=[],a={},r=0;r<i.length;r++)n=n.concat(this._getLinkedTasks(i[r],a,e));
return n},_getLinkedTasks:function(e,i,n){var a=void 0===e?t.config.root_id:e,r=i||{},s=t.isTaskExists(a)?t.getTask(a):this.getVirtualRoot(),o=t._getSuccessors(s);n&&o.push.apply(o,t._getPredecessors(s));for(var _=[],l=0;l<o.length;l++)r[this.getKey(o[l])]||(r[this.getKey(o[l])]=!0,_=_.concat(this._getLinkedTasks(o[l].target,r,!0)));for(var d=t.getChildren(s.id),l=0;l<d.length;l++)o=o.concat(this._getLinkedTasks(d[l],r,!0));return this.filterDuplicates(o.concat(_))},findLoops:function(e){var i=[];
t._forEach(e,function(t){t.target==t.source&&i.push([t.target,t.source])});var n=t._autoSchedulingGraph,a=n.getVertices(e),r=n.tarjanStronglyConnectedComponents(a,e);return t._forEach(r,function(t){t.tasks.length>1&&i.push(t)}),i}},t._autoSchedulingDateResolver={isFirstSmaller:function(e,i){return e.valueOf()<i.valueOf()&&t._hasDuration(e,i)?!0:!1},isSmallerOrDefault:function(t,e){return!(t&&!this.isFirstSmaller(t,e))},resolveRelationDate:function(e,i,n){for(var a=null,r=null,s=null,o=0;o<i.length;o++){
var _=i[o];e=_.target,s=_.preferredStart;var l=this.getConstraintDate(_,n);this.isSmallerOrDefault(s,l)&&this.isSmallerOrDefault(a,l)&&(a=l,r=_.id)}return a&&(a=t.getClosestWorkTime({date:a,dir:"future"})),{link:r,task:e,start_date:a}},getConstraintDate:function(e,i){var n=i(e.source);return n&&e.lag&&1*e.lag==e.lag&&(n=t.calculateEndDate(n,1*e.lag)),n}},t._autoSchedulingPlanner={generatePlan:function(e){function i(e){var i=s[e],n=t.getTask(e);return i&&(i.start_date||i.end_date)?i.end_date?i.end_date:t.calculateEndDate(i.start_date,n.duration,t.config.duration_unit):t.getClosestWorkTime({
date:n.end_date,dir:"future"})}var n=t._autoSchedulingGraph,a=n.topologicalSort(e),r={},s={};t._arrayMap(a,function(e){var i=t.getTask(e);i.auto_scheduling!==!1&&(r[e]=[],s[e]=null)});for(var o=0;o<e.length;o++)r[e[o].target]&&r[e[o].target].push(e[o]);for(var _=t._autoSchedulingDateResolver,l=[],o=0;o<a.length;o++){var d=a[o],h=_.resolveRelationDate(d,r[d]||[],i);if(h.start_date&&t.isLinkExists(h.link)){var c=t.getLink(h.link),u=t.getTask(d),g=t.getTask(c.source);if(u.start_date.valueOf()!==h.start_date.valueOf()&&t.callEvent("onBeforeTaskAutoSchedule",[u,h.start_date,c,g])===!1)continue;
}s[d]=h,h.start_date&&l.push(h)}return l},applyProjectPlan:function(e){for(var i,n,a,r,s=[],o=0;o<e.length;o++)if(a=null,r=null,i=e[o],i.task){n=t.getTask(i.task),i.link&&(a=t.getLink(i.link),r=t.getTask(a.source));var _=null;i.start_date&&n.start_date.valueOf()!=i.start_date.valueOf()&&(_=i.start_date),_&&(n.start_date=_,n.end_date=t.calculateEndDate(n.start_date,n.duration,t.config.duration_unit),s.push(n.id),t.callEvent("onAfterTaskAutoSchedule",[n,_,a,r]))}return s}},t._autoSchedulingPreferredDates=function(e,i){
for(var n=0;n<i.length;n++){var a=i[n],r=t.getTask(a.target);t.config.auto_scheduling_strict&&a.target!=e||(a.preferredStart=new Date(r.start_date))}},t._autoSchedule=function(e,i,n){if(t.callEvent("onBeforeAutoSchedule",[e])!==!1){t._autoscheduling_in_progress=!0;var a=t._autoSchedulingPath,r=[],s=a.findLoops(i);if(s.length)t.callEvent("onAutoScheduleCircularLink",[s]);else{var o=t._autoSchedulingPlanner;t._autoSchedulingPreferredDates(e,i);var _=o.generatePlan(i);r=o.applyProjectPlan(_),n&&n(r);
}return t._autoscheduling_in_progress=!1,t.callEvent("onAfterAutoSchedule",[e,r]),r}},t.autoSchedule=function(e,i){i=void 0===i?!0:!!i;var n=t._autoSchedulingPath.getLinkedTasks(e,i);t._autoSchedule(e,n,t._finalizeAutoSchedulingChanges)},t._finalizeAutoSchedulingChanges=function(e){t.batchUpdate(function(){for(var i=0;i<e.length;i++)t.updateTask(e[i])})},t.isCircularLink=function(e){return!!t._getConnectedGroup(e)},t._getConnectedGroup=function(e){var i=t._autoSchedulingPath,n=i.getLinkedTasks();t.isLinkExists(e.id)||(n=n.concat(t._formatLink(e)));
for(var a=i.findLoops(n),r=!1,s=0;s<a.length&&!r;s++)for(var o=a[s].links,_=0;_<o.length;_++)if(o[_]==e.id)return a[s];return null},t.findCycles=function(){var e=t._autoSchedulingPath,i=e.getLinkedTasks();return e.findLoops(i)},t._attachAutoSchedulingHandlers=function(){t._autoScheduleAfterLinkChange=function(e,i){t.config.auto_scheduling&&!this._autoscheduling_in_progress&&t.autoSchedule(i.source)},t.attachEvent("onAfterLinkUpdate",t._autoScheduleAfterLinkChange),t.attachEvent("onAfterLinkAdd",t._autoScheduleAfterLinkChange),
t.attachEvent("onParse",function(){t.config.auto_scheduling&&t.config.auto_scheduling_initial&&t.autoSchedule()}),t._preventCircularLink=function(e,i){return t.isCircularLink(i)?(t.callEvent("onCircularLinkError",[i,t._getConnectedGroup(i)]),!1):!0},t._preventDescendantLink=function(e,i){var n=t.getTask(i.source),a=t.getTask(i.target);return!t.config.auto_scheduling_descendant_links&&(t.isChildOf(n.id,a.id)&&t._isProject(a)||t.isChildOf(a.id,n.id)&&t._isProject(n))?!1:!0},t.attachEvent("onBeforeLinkAdd",t._preventCircularLink),
t.attachEvent("onBeforeLinkAdd",t._preventDescendantLink),t.attachEvent("onBeforeLinkUpdate",t._preventCircularLink),t.attachEvent("onBeforeLinkUpdate",t._preventDescendantLink),t._datesNotEqual=function(t,e){return t.valueOf()>e.valueOf()?this._hasDuration(e,t):this._hasDuration(t,e)},t._notEqualTaskDates=function(e,i){return this._datesNotEqual(e.start_date,i.start_date)||(this._datesNotEqual(e.end_date,i.end_date)||e.duration!=i.duration)&&e.type!=t.config.types.milestone?!0:void 0};var e,i;t.attachEvent("onBeforeTaskDrag",function(n,a,r){
return t.config.auto_scheduling_move_projects&&(e=t._autoSchedulingPath.getLinkedTasks(n,!0),i=n),!0}),t._autoScheduleAfterDND=function(n,a){if(t.config.auto_scheduling&&!this._autoscheduling_in_progress){var r=this.getTask(n);t._notEqualTaskDates(a,r)&&(t.config.auto_scheduling_move_projects&&i==n?t._autoSchedule(n,e,t._finalizeAutoSchedulingChanges):t.autoSchedule(r.id))}return e=null,i=null,!0},t._lightBoxChangesHandler=function(e,i){if(t.config.auto_scheduling&&!this._autoscheduling_in_progress){
var n=this.getTask(e);t._notEqualTaskDates(i,n)&&(t._autoschedule_lightbox_id=e)}return!0},t._lightBoxSaveHandler=function(e,i){return t.config.auto_scheduling&&!this._autoscheduling_in_progress&&t._autoschedule_lightbox_id&&t._autoschedule_lightbox_id==e&&(t._autoschedule_lightbox_id=null,t.autoSchedule(i.id)),!0},t.attachEvent("onBeforeTaskChanged",function(e,i,n){return t._autoScheduleAfterDND(e,n)}),t.attachEvent("onLightboxSave",t._lightBoxChangesHandler),t.attachEvent("onAfterTaskUpdate",t._lightBoxSaveHandler);
},t.attachEvent("onGanttReady",function(){t._attachAutoSchedulingHandlers()})});
//# sourceMappingURL=../sources/ext/dhtmlxgantt_auto_scheduling.js.map