/*
@license
dhtmlxScheduler v.4.3.25 Professional

This software is covered by DHTMLX Commercial License. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
scheduler._temp_matrix_scope=function(){function e(){for(var e=scheduler.get_visible_events(),t=[],a=0;a<this.y_unit.length;a++)t[a]=[];var r;t[r]||(t[r]=[]);for(var a=0;a<e.length;a++){r=this.order[e[a][this.y_property]];for(var n=0;this._trace_x[n+1]&&e[a].start_date>=this._trace_x[n+1];)n++;for(;this._trace_x[n]&&e[a].end_date>this._trace_x[n];)t[r][n]||(t[r][n]=[]),t[r][n].push(e[a]),n++}return t}function t(e,t,a){var r=0,n=a._step,i=a.round_position,d=0,l=t?e.end_date:e.start_date;l.valueOf()>scheduler._max_date.valueOf()&&(l=scheduler._max_date);
var s=l-scheduler._min_date_timeline;if(s>0){var o=scheduler._get_date_index(a,l);scheduler._ignores[o]&&(i=!0);for(var _=0;o>_;_++)r+=scheduler._cols[_];var c=scheduler.date.add(scheduler._min_date_timeline,scheduler.matrix[scheduler._mode].x_step*o,scheduler.matrix[scheduler._mode].x_unit);i?+l>+c&&t&&(d=scheduler._cols[o]):(s=l-c,a.first_hour||a.last_hour?(s-=a._start_correction,0>s&&(s=0),d=Math.round(s/n),d>scheduler._cols[o]&&(d=scheduler._cols[o])):d=Math.round(s/n))}return r+=t?0===s||i?d-14:d-12:d+1;
}function a(e,t){var a=scheduler._get_date_index(this,e),r=this._trace_x[a];return t&&+e!=+this._trace_x[a]&&(r=this._trace_x[a+1]?this._trace_x[a+1]:scheduler.date.add(this._trace_x[a],this.x_step,this.x_unit)),new Date(r)}function r(e){if(scheduler._ignores_detected)for(var t,a,r,n,i=0;i<e.length;i++){for(n=e[i],r=!1,t=scheduler._get_date_index(this,n.start_date),a=scheduler._get_date_index(this,n.end_date);a>t;){if(!scheduler._ignores[t]){r=!0;break}t++}r||t!=a||scheduler._ignores[a]||+n.end_date>+this._trace_x[a]&&(r=!0),
r||(e.splice(i,1),i--)}}function n(e){var t="";if(e&&"cell"!=this.render){r.call(this,e),e.sort(this.sort||function(e,t){return e.start_date.valueOf()==t.start_date.valueOf()?e.id>t.id?1:-1:e.start_date>t.start_date?1:-1});for(var n=[],i=e.length,d=0;i>d;d++){var l=e[d];l._inner=!1;var s=this.round_position?a.apply(this,[l.start_date,!1]):l.start_date;for(this.round_position?a.apply(this,[l.end_date,!0]):l.end_date;n.length;){var o=n[n.length-1];if(!(o.end_date.valueOf()<=s.valueOf()))break;n.splice(n.length-1,1);
}for(var _=!1,c=0;c<n.length;c++){var h=n[c];if(h.end_date.valueOf()<=s.valueOf()){_=!0,l._sorder=h._sorder,n.splice(c,1),l._inner=!0;break}}if(n.length&&(n[n.length-1]._inner=!0),!_)if(n.length)if(n.length<=n[n.length-1]._sorder){if(n[n.length-1]._sorder)for(var u=0;u<n.length;u++){for(var p=!1,v=0;v<n.length;v++)if(n[v]._sorder==u){p=!0;break}if(!p){l._sorder=u;break}}else l._sorder=0;l._inner=!0}else{for(var m=n[0]._sorder,g=1;g<n.length;g++)n[g]._sorder>m&&(m=n[g]._sorder);l._sorder=m+1,l._inner=!1;
}else l._sorder=0;n.push(l),n.length>(n.max_count||0)?(n.max_count=n.length,l._count=n.length):l._count=l._count?l._count:1}for(var f=0;f<e.length;f++)e[f]._count=n.max_count;for(var b=0;i>b;b++)t+=scheduler.render_timeline_event.call(this,e[b],!1)}return t}function i(t){var a="<table style='table-layout:fixed;' cellspacing='0' cellpadding='0'>",r=[];if(scheduler._load_mode&&scheduler._load(),"cell"==this.render)r=e.call(this);else for(var i=scheduler.get_visible_events(),d=this.order,l=0;l<i.length;l++){
var s=i[l],o=s[this.y_property],_=this.order[o];if(this.show_unassigned&&!o){for(var c in d)if(d.hasOwnProperty(c)){_=d[c],r[_]||(r[_]=[]);var h=scheduler._lame_copy({},s);h[this.y_property]=c,r[_].push(h)}}else r[_]||(r[_]=[]),r[_].push(s)}for(var u=0,p=0;p<scheduler._cols.length;p++)u+=scheduler._cols[p];var v=new Date,m=scheduler._cols.length-scheduler._ignores_detected;v=(scheduler.date.add(v,this.x_step*m,this.x_unit)-v-(this._start_correction+this._end_correction)*m)/u,this._step=v,this._summ=u;
var g=scheduler._colsS.heights=[],f=[];this._events_height={},this._section_height={};for(var p=0;p<this.y_unit.length;p++){var b=this._logic(this.render,this.y_unit[p],this);scheduler._merge(b,{height:this.dy}),this.section_autoheight&&(this.y_unit.length*b.height<t.offsetHeight&&(b.height=Math.max(b.height,Math.floor((t.offsetHeight-1)/this.y_unit.length))),this._section_height[this.y_unit[p].key]=b.height),b.td_className||(b.td_className="dhx_matrix_scell"+(scheduler.templates[this.name+"_scaley_class"](this.y_unit[p].key,this.y_unit[p].label,this.y_unit[p])?" "+scheduler.templates[this.name+"_scaley_class"](this.y_unit[p].key,this.y_unit[p].label,this.y_unit[p]):"")),
b.td_content||(b.td_content=scheduler.templates[this.name+"_scale_label"](this.y_unit[p].key,this.y_unit[p].label,this.y_unit[p])),scheduler._merge(b,{tr_className:"",style_height:"height:"+b.height+"px;",style_width:"width:"+(this.dx-1)+"px;",summ_width:"width:"+u+"px;",table_className:""});var y=n.call(this,r[p]);if(this.fit_events){var x=this._events_height[this.y_unit[p].key]||0;b.height=x>b.height?x:b.height,b.style_height="height:"+b.height+"px;",this._section_height[this.y_unit[p].key]=b.height;
}if(a+="<tr class='"+b.tr_className+"' style='"+b.style_height+"'><td class='"+b.td_className+"' style='"+b.style_width+" height:"+(b.height-1)+"px;'>"+b.td_content+"</td>","cell"==this.render)for(var l=0;l<scheduler._cols.length;l++)a+=scheduler._ignores[l]?"<td></td>":"<td class='dhx_matrix_cell "+scheduler.templates[this.name+"_cell_class"](r[p][l],this._trace_x[l],this.y_unit[p])+"' style='width:"+(scheduler._cols[l]-1)+"px'><div style='width:"+(scheduler._cols[l]-1)+"px'>"+scheduler.templates[this.name+"_cell_value"](r[p][l],this._trace_x[l],this.y_unit[p])+"</div></td>";else{
a+="<td><div style='"+b.summ_width+" "+b.style_height+" position:relative;' class='dhx_matrix_line'>",a+=y,a+="<table class='"+b.table_className+"' cellpadding='0' cellspacing='0' style='"+b.summ_width+" "+b.style_height+"' >";for(var l=0;l<scheduler._cols.length;l++)a+=scheduler._ignores[l]?"<td></td>":"<td class='dhx_matrix_cell "+scheduler.templates[this.name+"_cell_class"](r[p],this._trace_x[l],this.y_unit[p])+"' style='width:"+(scheduler._cols[l]-1)+"px'><div style='width:"+(scheduler._cols[l]-1)+"px'></div></td>";
a+="</table>",a+="</div></td>"}a+="</tr>",f.push(b)}a+="</table>",this._matrix=r,t.innerHTML=a,scheduler._rendered=[];for(var k=scheduler._obj.getElementsByTagName("DIV"),p=0;p<k.length;p++)k[p].getAttribute("event_id")&&scheduler._rendered.push(k[p]);this._scales={};for(var w=t.firstChild.rows,D=null,p=0,E=f.length;E>p;p++){D=this.y_unit[p],g.push(f[p].height);var M=D.key,N=this._scales[M]=scheduler._isRender("cell")?w[p]:w[p].childNodes[1].getElementsByTagName("div")[0];scheduler.callEvent("onScaleAdd",[N,M]);
}}function d(e){var t=scheduler._min_date,a=scheduler._max_date;scheduler._process_ignores(t,this.x_size,this.x_unit,this.x_step,e);for(var r=(this.x_size+(e?scheduler._ignores_detected:0),0),n=0;+a>+t;)if(this._trace_x[n]=new Date(t),t=scheduler.date.add(t,this.x_step,this.x_unit),scheduler.date[this.x_unit+"_start"]&&(t=scheduler.date[this.x_unit+"_start"](t)),scheduler._ignores[n]||r++,n++,e)if(r<this.x_size&&!(+a>+t))a=scheduler.date["add_"+this.name+"_private"](a,(this.x_length||this.x_size)*this.x_step);else if(r>=this.x_size){
scheduler._max_date=t;break}return{total:n,displayed:r}}function l(e){var t=scheduler.xy.scale_height,a=this._header_resized||scheduler.xy.scale_height;scheduler._cols=[],scheduler._colsS={height:0},this._trace_x=[];var r=scheduler._x-this.dx-scheduler.xy.scroll_width,n=[this.dx],i=scheduler._els.dhx_cal_header[0];i.style.width=n[0]+r+"px";for(var l=scheduler._min_date_timeline=scheduler._min_date,o=scheduler.config.preserve_scale_length,_=d.call(this,o),c=_.displayed,h=_.total,u=0;h>u;u++)scheduler._ignores[u]?(scheduler._cols[u]=0,
c++):scheduler._cols[u]=Math.floor(r/(c-u)),r-=scheduler._cols[u],n[u+1]=n[u]+scheduler._cols[u];if(e.innerHTML="<div></div>",this.second_scale){for(var v=this.second_scale.x_unit,m=[this._trace_x[0]],g=[],f=[this.dx,this.dx],b=0,y=0;y<this._trace_x.length;y++){var x=this._trace_x[y],k=s(v,x,m[b]);k&&(++b,m[b]=x,f[b+1]=f[b]);var w=b+1;g[b]=scheduler._cols[y]+(g[b]||0),f[w]+=scheduler._cols[y]}e.innerHTML="<div></div><div></div>";var D=e.firstChild;D.style.height=a+"px";var E=e.lastChild;E.style.position="relative";
for(var M=0;M<m.length;M++){var N=m[M],S=scheduler.templates[this.name+"_second_scalex_class"](N),O=document.createElement("DIV");O.className="dhx_scale_bar dhx_second_scale_bar"+(S?" "+S:""),scheduler.set_xy(O,g[M]-1,a-3,f[M],0),O.innerHTML=scheduler.templates[this.name+"_second_scale_date"](N),D.appendChild(O)}}scheduler.xy.scale_height=a,e=e.lastChild;for(var T=0;T<this._trace_x.length;T++)if(!scheduler._ignores[T]){l=this._trace_x[T],scheduler._render_x_header(T,n[T],l,e);var C=scheduler.templates[this.name+"_scalex_class"](l);
C&&(e.lastChild.className+=" "+C)}scheduler.xy.scale_height=t;var L=this._trace_x;e.onclick=function(e){var t=p(e);t&&scheduler.callEvent("onXScaleClick",[t.x,L[t.x],e||event])},e.ondblclick=function(e){var t=p(e);t&&scheduler.callEvent("onXScaleDblClick",[t.x,L[t.x],e||event])}}function s(e,t,a){switch(e){case"hour":return t.getHours()!=a.getHours()||s("day",t,a);case"day":return!(t.getDate()==a.getDate()&&t.getMonth()==a.getMonth()&&t.getFullYear()==a.getFullYear());case"week":return!(scheduler.date.week_start(new Date(t)).valueOf()==scheduler.date.week_start(new Date(a)).valueOf());
case"month":return!(t.getMonth()==a.getMonth()&&t.getFullYear()==a.getFullYear());case"year":return!(t.getFullYear()==a.getFullYear());default:return!1}}function o(e){if(this._header_resized&&(!e||!this.second_scale)){scheduler.xy.scale_height/=2,this._header_resized=!1;var t=scheduler._els.dhx_cal_header[0];t.className=t.className.replace(/ dhx_second_cal_header/gi,"")}}function _(e){if(o.call(this,e),e){this.second_scale&&!this._header_resized&&(this._header_resized=scheduler.xy.scale_height,scheduler.xy.scale_height*=2,
scheduler._els.dhx_cal_header[0].className+=" dhx_second_cal_header"),scheduler.set_sizes(),scheduler._init_matrix_tooltip();var t=scheduler._min_date;l.call(this,scheduler._els.dhx_cal_header[0]),i.call(this,scheduler._els.dhx_cal_data[0]),scheduler._min_date=t,scheduler._els.dhx_cal_date[0].innerHTML=scheduler.templates[this.name+"_date"](scheduler._min_date,scheduler._max_date),scheduler._mark_now&&scheduler._mark_now(),o.call(this,e)}c()}function c(){scheduler._tooltip&&(scheduler._tooltip.style.display="none",
scheduler._tooltip.date="")}function h(e,t,a){if("cell"==e.render){var r=t.x+"_"+t.y,n=e._matrix[t.y][t.x];if(!n)return c();if(n.sort(function(e,t){return e.start_date>t.start_date?1:-1}),scheduler._tooltip){if(scheduler._tooltip.date==r)return;scheduler._tooltip.innerHTML=""}else{var i=scheduler._tooltip=document.createElement("DIV");i.className="dhx_year_tooltip",document.body.appendChild(i),i.onclick=scheduler._click.dhx_cal_data}for(var d="",l=0;l<n.length;l++){var s=n[l].color?"background-color:"+n[l].color+";":"",o=n[l].textColor?"color:"+n[l].textColor+";":"";
d+="<div class='dhx_tooltip_line' event_id='"+n[l].id+"' style='"+s+o+"'>",d+="<div class='dhx_tooltip_date'>"+(n[l]._timed?scheduler.templates.event_date(n[l].start_date):"")+"</div>",d+="<div class='dhx_event_icon icon_details'>&nbsp;</div>",d+=scheduler.templates[e.name+"_tooltip"](n[l].start_date,n[l].end_date,n[l])+"</div>"}scheduler._tooltip.style.display="",scheduler._tooltip.style.top="0px",document.body.offsetWidth-a.left-scheduler._tooltip.offsetWidth<0?scheduler._tooltip.style.left=a.left-scheduler._tooltip.offsetWidth+"px":scheduler._tooltip.style.left=a.left+t.src.offsetWidth+"px",
scheduler._tooltip.date=r,scheduler._tooltip.innerHTML=d,document.body.offsetHeight-a.top-scheduler._tooltip.offsetHeight<0?scheduler._tooltip.style.top=a.top-scheduler._tooltip.offsetHeight+t.src.offsetHeight+"px":scheduler._tooltip.style.top=a.top+"px"}}function u(e){for(var t=e.parentNode.childNodes,a=0;a<t.length;a++)if(t[a]==e)return a;return-1}function p(e){e=e||event;for(var t=e.target?e.target:e.srcElement;t&&"DIV"!=t.tagName;)t=t.parentNode;if(t&&"DIV"==t.tagName){var a=t.className.split(" ")[0];
if("dhx_scale_bar"==a)return{x:u(t),y:-1,src:t,scale:!0}}}scheduler.matrix={},scheduler._merge=function(e,t){for(var a in t)"undefined"==typeof e[a]&&(e[a]=t[a])},scheduler.createTimelineView=function(e){scheduler._skin_init(),scheduler._merge(e,{section_autoheight:!0,name:"matrix",x:"time",y:"time",x_step:1,x_unit:"hour",y_unit:"day",y_step:1,x_start:0,x_size:24,y_start:0,y_size:7,render:"cell",dx:200,dy:50,event_dy:scheduler.xy.bar_height-5,event_min_dy:scheduler.xy.bar_height-5,resize_events:!0,
fit_events:!0,show_unassigned:!1,second_scale:!1,round_position:!1,_logic:function(e,t,a){var r={};return scheduler.checkEvent("onBeforeSectionRender")&&(r=scheduler.callEvent("onBeforeSectionRender",[e,t,a])),r}}),e._original_x_start=e.x_start,"day"!=e.x_unit&&(e.first_hour=e.last_hour=0),e._start_correction=e.first_hour?60*e.first_hour*60*1e3:0,e._end_correction=e.last_hour?60*(24-e.last_hour)*60*1e3:0,scheduler.checkEvent("onTimelineCreated")&&scheduler.callEvent("onTimelineCreated",[e]);var t=scheduler.render_data;
scheduler.render_data=function(a,r){if(this._mode!=e.name)return t.apply(this,arguments);if(r&&!e.show_unassigned&&"cell"!=e.render)for(var n=0;n<a.length;n++)this.clear_event(a[n]),this.render_timeline_event.call(this.matrix[this._mode],a[n],!0);else scheduler._renderMatrix.call(e,!0,!0)},scheduler.matrix[e.name]=e,scheduler.templates[e.name+"_cell_value"]=function(e){return e?e.length:""},scheduler.templates[e.name+"_cell_class"]=function(e){return""},scheduler.templates[e.name+"_scalex_class"]=function(e){
return""},scheduler.templates[e.name+"_second_scalex_class"]=function(e){return""},scheduler.templates[e.name+"_scaley_class"]=function(e,t,a){return""},scheduler.templates[e.name+"_scale_label"]=function(e,t,a){return t},scheduler.templates[e.name+"_tooltip"]=function(e,t,a){return a.text},scheduler.templates[e.name+"_date"]=function(e,t){return e.getDay()==t.getDay()&&864e5>t-e||+e==+scheduler.date.date_part(new Date(t))||+scheduler.date.add(e,1,"day")==+t&&0===t.getHours()&&0===t.getMinutes()?scheduler.templates.day_date(e):e.getDay()!=t.getDay()&&864e5>t-e?scheduler.templates.day_date(e)+" &ndash; "+scheduler.templates.day_date(t):scheduler.templates.week_date(e,t);
},scheduler.templates[e.name+"_scale_date"]=scheduler.date.date_to_str(e.x_date||scheduler.config.hour_date),scheduler.templates[e.name+"_second_scale_date"]=scheduler.date.date_to_str(e.second_scale&&e.second_scale.x_date?e.second_scale.x_date:scheduler.config.hour_date),scheduler.date["add_"+e.name+"_private"]=function(t,a){var r=a,n=e.x_unit;if("minute"==e.x_unit||"hour"==e.x_unit){var i=r;"hour"==e.x_unit&&(i*=60),i%1440||(r=i/1440,n="day")}return scheduler.date.add(t,r,n)},scheduler.date["add_"+e.name]=function(t,a,r){
var n=scheduler.date["add_"+e.name+"_private"](t,(e.x_length||e.x_size)*e.x_step*a);if("minute"==e.x_unit||"hour"==e.x_unit){var i=e.x_length||e.x_size,d="hour"==e.x_unit?60*e.x_step:e.x_step;if(d*i%1440)if(+scheduler.date.date_part(new Date(t))==+scheduler.date.date_part(new Date(n)))e.x_start+=a*i;else{var l=1440/(i*d)-1,s=Math.round(l*i);a>0?e.x_start=e.x_start-s:e.x_start=s+e.x_start}}return n},scheduler.date[e.name+"_start"]=function(t){var a=scheduler.date[e.x_unit+"_start"]||scheduler.date.day_start,r=a.call(scheduler.date,t);
return r=scheduler.date.add(r,e.x_step*e.x_start,e.x_unit)},scheduler.callEvent("onOptionsLoad",[e]),scheduler[e.name+"_view"]=function(t){t?scheduler._set_timeline_dates(e):scheduler._renderMatrix.apply(e,arguments)};var r=new Date;scheduler.date.add(r,e.x_step,e.x_unit).valueOf()-r.valueOf();scheduler["mouse_"+e.name]=function(t){var r=this._drag_event;this._drag_id&&(r=this.getEvent(this._drag_id)),t.x-=e.dx;var n=scheduler._timeline_drag_date(e,t.x);if(t.x=0,t.force_redraw=!0,t.custom=!0,"move"==this._drag_mode&&this._drag_id&&this._drag_event){
var r=this.getEvent(this._drag_id),i=this._drag_event;if(t._ignores=this._ignores_detected||e._start_correction||e._end_correction,void 0===i._move_delta&&(i._move_delta=(r.start_date-n)/6e4,this.config.preserve_length&&t._ignores&&(i._move_delta=this._get_real_event_length(r.start_date,n,e),i._event_length=this._get_real_event_length(r.start_date,r.end_date,e))),this.config.preserve_length&&t._ignores){var d=(i._event_length,this._get_fictional_event_length(n,i._move_delta,e,!0));n=new Date(n-d);
}else n=scheduler.date.add(n,i._move_delta,"minute")}if("resize"==this._drag_mode&&r&&(!this.config.timeline_swap_resize&&this._drag_id&&(this._drag_from_start&&+n>+r.end_date?this._drag_from_start=!1:!this._drag_from_start&&+n<+r.start_date&&(this._drag_from_start=!0)),t.resize_from_start=this._drag_from_start,!this.config.timeline_swap_resize&&this._drag_id&&this._drag_from_start&&+n>=+scheduler.date.add(r.end_date,-scheduler.config.time_step,"minute")&&(n=scheduler.date.add(r.end_date,-scheduler.config.time_step,"minute"))),
e.round_position)switch(this._drag_mode){case"move":this.config.preserve_length||(n=a.call(e,n,!1),"day"==e.x_unit&&(t.custom=!1));break;case"resize":this._drag_event&&((null===this._drag_event._resize_from_start||void 0===this._drag_event._resize_from_start)&&(this._drag_event._resize_from_start=t.resize_from_start),t.resize_from_start=this._drag_event._resize_from_start,n=a.call(e,n,!this._drag_event._resize_from_start))}this._resolve_timeline_section(e,t),t.section&&this._update_timeline_section({
pos:t,event:this.getEvent(this._drag_id),view:e}),t.y=Math.round((this._correct_shift(n,1)-this._min_date)/(6e4*this.config.time_step)),t.shift=this.config.time_step;var l=this._is_pos_changed(this._drag_pos,t);return this._drag_pos&&l&&(this._drag_event._dhx_changed=!0),l||this._drag_pos.has_moved||(t.force_redraw=!1),t}},scheduler._get_timeline_event_height=function(e,t){var a=e[t.y_property],r=t.event_dy;return"full"==t.event_dy&&(r=t.section_autoheight?t._section_height[a]-6:t.dy-3),t.resize_events&&(r=Math.max(Math.floor(r/e._count),t.event_min_dy)),
r},scheduler._get_timeline_event_y=function(e,t){var a=e,r=2+a*t+(a?2*a:0);return scheduler.config.cascade_event_display&&(r=2+a*scheduler.config.cascade_event_margin+(a?2*a:0)),r},scheduler.render_timeline_event=function(e,a){var r=e[this.y_property];if(!r)return"";var n=e._sorder,i=t(e,!1,this),d=t(e,!0,this),l=scheduler._get_timeline_event_height(e,this),s=l-2;e._inner||"full"!=this.event_dy||(s=(s+2)*(e._count-n)-2);var o=scheduler._get_timeline_event_y(e._sorder,l),_=l+o+2;(!this._events_height[r]||this._events_height[r]<_)&&(this._events_height[r]=_);
var c=scheduler.templates.event_class(e.start_date,e.end_date,e);c="dhx_cal_event_line "+(c||""),e._no_drag_move&&(c+=" no_drag_move");var h=e.color?"background:"+e.color+";":"",u=e.textColor?"color:"+e.textColor+";":"",p=scheduler.templates.event_bar_text(e.start_date,e.end_date,e),v='<div event_id="'+e.id+'" class="'+c+'" style="'+h+u+"position:absolute; top:"+o+"px; height: "+s+"px; left:"+i+"px; width:"+Math.max(0,d-i)+"px;"+(e._text_style||"")+'">';if(scheduler.config.drag_resize&&!scheduler.config.readonly){
var m="dhx_event_resize",g="<div class='"+m+" "+m+"_start' style='height: "+s+"px;'></div>",f="<div class='"+m+" "+m+"_end' style='height: "+s+"px;'></div>";v+=(e._no_resize_start?"":g)+(e._no_resize_end?"":f)}if(v+=p+"</div>",!a)return v;var b=document.createElement("DIV");b.innerHTML=v;var y=this.order[r],x=scheduler._els.dhx_cal_data[0].firstChild.rows[y];if(x){var k=x.cells[1].firstChild;scheduler._rendered.push(b.firstChild),k.appendChild(b.firstChild)}},scheduler._matrix_tooltip_handler=function(e){
var t=scheduler.matrix[scheduler._mode];if(t&&"cell"==t.render){if(t){var a=scheduler._locate_cell_timeline(e),e=e||event;e.target||e.srcElement;if(a)return h(t,a,getOffset(a.src))}c()}},scheduler._init_matrix_tooltip=function(){scheduler._detachDomEvent(scheduler._els.dhx_cal_data[0],"mouseover",scheduler._matrix_tooltip_handler),dhtmlxEvent(scheduler._els.dhx_cal_data[0],"mouseover",scheduler._matrix_tooltip_handler)},scheduler._set_timeline_dates=function(e){scheduler._min_date=scheduler.date[e.name+"_start"](new Date(scheduler._date)),
scheduler._max_date=scheduler.date["add_"+e.name+"_private"](scheduler._min_date,e.x_size*e.x_step),scheduler.date[e.x_unit+"_start"]&&(scheduler._max_date=scheduler.date[e.x_unit+"_start"](scheduler._max_date)),scheduler._table_view=!0},scheduler._renderMatrix=function(e,t){t||(scheduler._els.dhx_cal_data[0].scrollTop=0),scheduler._set_timeline_dates(this),_.call(this,e)},scheduler._locate_cell_timeline=function(e){e=e||event;for(var t=e.target?e.target:e.srcElement,a={},r=scheduler.matrix[scheduler._mode],n=scheduler.getActionData(e),i=scheduler._ignores,d=0,l=0;l<r._trace_x.length-1&&!(+n.date<r._trace_x[l+1]);l++)i[l]||d++;
a.x=0===d?0:l,a.y=r.order[n.section];var s=scheduler._isRender("cell")?1:0;a.src=r._scales[n.section]?r._scales[n.section].getElementsByTagName("td")[l+s]:null;for(var o=!1;0===a.x&&"dhx_cal_data"!=t.className&&t.parentNode;){if("dhx_matrix_scell"==t.className.split(" ")[0]){o=!0;break}t=t.parentNode}return o?(a.x=-1,a.src=t,a.scale=!0):a.x=l,a};var v=scheduler._click.dhx_cal_data;scheduler._click.dhx_marked_timespan=scheduler._click.dhx_cal_data=function(e){var t=v.apply(this,arguments),a=scheduler.matrix[scheduler._mode];
if(a){var r=scheduler._locate_cell_timeline(e);r&&(r.scale?scheduler.callEvent("onYScaleClick",[r.y,a.y_unit[r.y],e||event]):scheduler.callEvent("onCellClick",[r.x,r.y,a._trace_x[r.x],(a._matrix[r.y]||{})[r.x]||[],e||event]))}return t},scheduler.dblclick_dhx_matrix_cell=function(e){var t=scheduler.matrix[scheduler._mode];if(t){var a=scheduler._locate_cell_timeline(e);a&&(a.scale?scheduler.callEvent("onYScaleDblClick",[a.y,t.y_unit[a.y],e||event]):scheduler.callEvent("onCellDblClick",[a.x,a.y,t._trace_x[a.x],(t._matrix[a.y]||{})[a.x]||[],e||event]));
}};var m=scheduler.dblclick_dhx_marked_timespan||function(){};scheduler.dblclick_dhx_marked_timespan=function(e){var t=scheduler.matrix[scheduler._mode];return t?scheduler.dblclick_dhx_matrix_cell(e):m.apply(this,arguments)},scheduler.dblclick_dhx_matrix_scell=function(e){return scheduler.dblclick_dhx_matrix_cell(e)},scheduler._isRender=function(e){return scheduler.matrix[scheduler._mode]&&scheduler.matrix[scheduler._mode].render==e},scheduler.attachEvent("onCellDblClick",function(e,t,a,r,n){if(!this.config.readonly&&("dblclick"!=n.type||this.config.dblclick_create)){
var i=scheduler.matrix[scheduler._mode],d={};d.start_date=i._trace_x[e],d.end_date=i._trace_x[e+1]?i._trace_x[e+1]:scheduler.date.add(i._trace_x[e],i.x_step,i.x_unit),i._start_correction&&(d.start_date=new Date(1*d.start_date+i._start_correction)),i._end_correction&&(d.end_date=new Date(d.end_date-i._end_correction)),d[i.y_property]=i.y_unit[t].key,scheduler.addEventNow(d,null,n)}}),scheduler.attachEvent("onBeforeDrag",function(e,t,a){return!scheduler._isRender("cell")}),scheduler.attachEvent("onEventChanged",function(e,t){
t._timed=this.isOneDayEvent(t)}),scheduler.attachEvent("onBeforeEventChanged",function(e,t,a,r){return e&&(e._move_delta=void 0),r&&(r._move_delta=void 0),!0}),scheduler._is_column_visible=function(e){var t=scheduler.matrix[scheduler._mode],a=scheduler._get_date_index(t,e);return!scheduler._ignores[a]};var g=scheduler._render_marked_timespan;scheduler._render_marked_timespan=function(e,a,r,n,i){if(!scheduler.config.display_marked_timespans)return[];if(scheduler.matrix&&scheduler.matrix[scheduler._mode]){
if(scheduler._isRender("cell"))return;var d=scheduler._lame_copy({},scheduler.matrix[scheduler._mode]);d.round_position=!1;var l=[],s=[],o=[],_=e.sections?e.sections.units||e.sections.timeline:null;if(r)o=[a],s=[r];else{var c=d.order;if(_)c.hasOwnProperty(_)&&(s.push(_),o.push(d._scales[_]));else for(var h in c)c.hasOwnProperty(h)&&(s.push(h),o.push(d._scales[h]))}var n=n?new Date(n):scheduler._min_date,i=i?new Date(i):scheduler._max_date;n.valueOf()<scheduler._min_date.valueOf()&&(n=new Date(scheduler._min_date)),
i.valueOf()>scheduler._max_date.valueOf()&&(i=new Date(scheduler._max_date));for(var u=0;u<d._trace_x.length&&!scheduler._is_column_visible(d._trace_x[u]);u++);if(u==d._trace_x.length)return;var p=[];if(e.days>6){var v=new Date(e.days);scheduler.date.date_part(new Date(n))<=+v&&+i>=+v&&p.push(v)}else p.push.apply(p,scheduler._get_dates_by_index(e.days));for(var m=e.zones,f=scheduler._get_css_classes_by_config(e),b=0;b<s.length;b++){a=o[b],r=s[b];for(var u=0;u<p.length;u++)for(var y=p[u],x=0;x<m.length;x+=2){
var k=m[x],w=m[x+1],D=new Date(+y+60*k*1e3),E=new Date(+y+60*w*1e3);if(E>n&&i>D){var M=scheduler._get_block_by_config(e);M.className=f;var N=t({start_date:D},!1,d)-1,S=t({start_date:E},!1,d)-1,O=Math.max(1,S-N-1),T=d._section_height[r]-1||d.dy-1;M.style.cssText="height: "+T+"px; left: "+N+"px; width: "+O+"px; top: 0;",a.insertBefore(M,a.firstChild),l.push(M)}}}return l}return g.apply(scheduler,[e,a,r])};var f=scheduler._append_mark_now;scheduler._append_mark_now=function(e,t){if(scheduler.matrix&&scheduler.matrix[scheduler._mode]){
var a=scheduler._currentDate(),r=scheduler._get_zone_minutes(a),n={days:+scheduler.date.date_part(a),zones:[r,r+1],css:"dhx_matrix_now_time",type:"dhx_now_time"};return scheduler._render_marked_timespan(n)}return f.apply(scheduler,[e,t])};var b=scheduler._mark_timespans;scheduler._mark_timespans=function(){if(scheduler.matrix&&scheduler.matrix[scheduler.getState().mode]){for(var e=[],t=scheduler.matrix[scheduler.getState().mode],a=t.y_unit,r=0;r<a.length;r++){var n=a[r].key,i=t._scales[n],d=scheduler._on_scale_add_marker(i,n);
e.push.apply(e,d)}return e}return b.apply(this,arguments)};var y=scheduler._on_scale_add_marker;scheduler._on_scale_add_marker=function(e,t){if(scheduler.matrix&&scheduler.matrix[scheduler._mode]){var a=[],r=scheduler._marked_timespans;if(r&&scheduler.matrix&&scheduler.matrix[scheduler._mode])for(var n=scheduler._mode,i=scheduler._min_date,d=scheduler._max_date,l=r.global,s=scheduler.date.date_part(new Date(i));d>s;s=scheduler.date.add(s,1,"day")){var o=+s,_=s.getDay(),c=[],h=l[o]||l[_];if(c.push.apply(c,scheduler._get_configs_to_render(h)),
r[n]&&r[n][t]){var u=[],p=scheduler._get_types_to_render(r[n][t][_],r[n][t][o]);u.push.apply(u,scheduler._get_configs_to_render(p)),u.length&&(c=u)}for(var v=0;v<c.length;v++){var m=c[v],g=m.days;7>g?(g=o,a.push.apply(a,scheduler._render_marked_timespan(m,e,t,s,scheduler.date.add(s,1,"day"))),g=_):a.push.apply(a,scheduler._render_marked_timespan(m,e,t,s,scheduler.date.add(s,1,"day")))}}return a}return y.apply(this,arguments)},scheduler._resolve_timeline_section=function(e,t){var a=0,r=0;for(a;a<this._colsS.heights.length&&(r+=this._colsS.heights[a],
!(r>t.y));a++);e.y_unit[a]||(a=e.y_unit.length-1),this._drag_event&&!this._drag_event._orig_section&&(this._drag_event._orig_section=e.y_unit[a].key),t.fields={},a>=0&&e.y_unit[a]&&(t.section=t.fields[e.y_property]=e.y_unit[a].key)},scheduler._update_timeline_section=function(e){var t=e.view,a=e.event,r=e.pos;if(a){if(a[t.y_property]!=r.section){var n=this._get_timeline_event_height(a,t);a._sorder=this._get_dnd_order(a._sorder,n,t._section_height[r.section])}a[t.y_property]=r.section}},scheduler._get_date_index=function(e,t){
for(var a=0,r=e._trace_x;a<r.length-1&&+t>=+r[a+1];)a++;return a},scheduler._timeline_drag_date=function(e,t){var a,r,n=e,i={x:t},d=0,l=0;for(l;l<=this._cols.length-1;l++)if(r=this._cols[l],d+=r,d>i.x){a=(i.x-(d-r))/r,a=0>a?0:a;break}if(n.round_position){var s=1;scheduler.getState().drag_mode&&"move"!=scheduler.getState().drag_mode&&(s=.5),a>=s&&l++,a=0}if(0===l&&this._ignores[0])for(l=1,a=0;this._ignores[l];)l++;else if(l==this._cols.length&&this._ignores[l-1]){for(l=this._cols.length-1,a=0;this._ignores[l];)l--;
l++}var o;if(l>=n._trace_x.length)o=scheduler.date.add(n._trace_x[n._trace_x.length-1],n.x_step,n.x_unit),n._end_correction&&(o=new Date(o-n._end_correction));else{var _=a*r*n._step+n._start_correction;o=new Date(+n._trace_x[l]+_)}return o},scheduler.attachEvent("onBeforeTodayDisplayed",function(){for(var e in scheduler.matrix){var t=scheduler.matrix[e];t.x_start=t._original_x_start}return!0}),scheduler.attachEvent("onOptionsLoad",function(){for(var e in scheduler.matrix){var t=scheduler.matrix[e];
t.order={},scheduler.callEvent("onOptionsLoadStart",[]);for(var e=0;e<t.y_unit.length;e++)t.order[t.y_unit[e].key]=e;scheduler.callEvent("onOptionsLoadFinal",[]),scheduler._date&&t.name==scheduler._mode&&scheduler.setCurrentView(scheduler._date,scheduler._mode)}}),scheduler.attachEvent("onSchedulerResize",function(){if(scheduler.matrix[this._mode]){var e=scheduler.matrix[this._mode];return scheduler._renderMatrix.call(e,!0,!0),!1}return!0}),scheduler.attachEvent("onBeforeDrag",function(e,t,a){if("resize"==t){
var r=a.target||a.srcElement;(r.className||"").indexOf("dhx_event_resize_end")<0?scheduler._drag_from_start=!0:scheduler._drag_from_start=!1}return!0})},scheduler._temp_matrix_scope();
//# sourceMappingURL=../sources/ext/dhtmlxscheduler_timeline.js.map