/*
@license
dhtmlxScheduler v.4.3.25 Professional

This software is covered by DHTMLX Commercial License. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
!function(){scheduler.config.container_autoresize=!0,scheduler.config.month_day_min_height=90,scheduler.config.min_grid_size=25,scheduler.config.min_map_size=400;var e=scheduler._pre_render_events,t=!0,a=0,i=0;scheduler._pre_render_events=function(n,l){if(!scheduler.config.container_autoresize||!t)return e.apply(this,arguments);var r=this.xy.bar_height,d=this._colsS.heights,o=this._colsS.heights=[0,0,0,0,0,0,0],s=this._els.dhx_cal_data[0];if(n=this._table_view?this._pre_render_events_table(n,l):this._pre_render_events_line(n,l),
this._table_view)if(l)this._colsS.heights=d;else{var _=s.firstChild;if(_.rows){for(var c=0;c<_.rows.length;c++){if(o[c]++,o[c]*r>this._colsS.height-this.xy.month_head_height){var u=_.rows[c].cells,h=this._colsS.height-this.xy.month_head_height;1*this.config.max_month_events!==this.config.max_month_events||o[c]<=this.config.max_month_events?h=o[c]*r:(this.config.max_month_events+1)*r>this._colsS.height-this.xy.month_head_height&&(h=(this.config.max_month_events+1)*r);for(var p=0;p<u.length;p++)u[p].childNodes[1].style.height=h+"px";
o[c]=(o[c-1]||0)+u[0].offsetHeight}o[c]=(o[c-1]||0)+_.rows[c].cells[0].offsetHeight}o.unshift(0),_.parentNode.offsetHeight<_.parentNode.scrollHeight&&!_._h_fix}else if(n.length||"visible"!=this._els.dhx_multi_day[0].style.visibility||(o[0]=-1),n.length||-1==o[0]){var v=(_.parentNode.childNodes,(o[0]+1)*r+1);i!=v+1&&(this._obj.style.height=a-i+v-1+"px"),v+="px",s.style.top=this._els.dhx_cal_navline[0].offsetHeight+this._els.dhx_cal_header[0].offsetHeight+parseInt(v,10)+"px",s.style.height=this._obj.offsetHeight-parseInt(s.style.top,10)-(this.xy.margin_top||0)+"px";
var m=this._els.dhx_multi_day[0];m.style.height=v,m.style.visibility=-1==o[0]?"hidden":"visible",m=this._els.dhx_multi_day[1],m.style.height=v,m.style.visibility=-1==o[0]?"hidden":"visible",m.className=o[0]?"dhx_multi_day_icon":"dhx_multi_day_icon_small",this._dy_shift=(o[0]+1)*r,o[0]=0}}return n};var n=["dhx_cal_navline","dhx_cal_header","dhx_multi_day","dhx_cal_data"],l=function(e){a=0;for(var t=0;t<n.length;t++){var l=n[t],r=scheduler._els[l]?scheduler._els[l][0]:null,d=0;switch(l){case"dhx_cal_navline":
case"dhx_cal_header":d=parseInt(r.style.height,10);break;case"dhx_multi_day":d=r?r.offsetHeight-1:0,i=d;break;case"dhx_cal_data":var o=scheduler.getState().mode;if(d=r.childNodes[1]&&"month"!=o?r.childNodes[1].offsetHeight:Math.max(r.offsetHeight-1,r.scrollHeight),"month"==o){if(scheduler.config.month_day_min_height&&!e){var s=r.getElementsByTagName("tr").length;d=s*scheduler.config.month_day_min_height}e&&(r.style.height=d+"px")}else if("year"==o)d=190*scheduler.config.year_y;else if("agenda"==o){
if(d=0,r.childNodes&&r.childNodes.length)for(var _=0;_<r.childNodes.length;_++)d+=r.childNodes[_].offsetHeight;d+2<scheduler.config.min_grid_size?d=scheduler.config.min_grid_size:d+=2}else if("week_agenda"==o){for(var c,u,h=scheduler.xy.week_agenda_scale_height+scheduler.config.min_grid_size,p=0;p<r.childNodes.length;p++){u=r.childNodes[p];for(var _=0;_<u.childNodes.length;_++){for(var v=0,m=u.childNodes[_].childNodes[1],b=0;b<m.childNodes.length;b++)v+=m.childNodes[b].offsetHeight;c=v+scheduler.xy.week_agenda_scale_height,
c=1!=p||2!=_&&3!=_?c:2*c,c>h&&(h=c)}}d=3*h}else if("map"==o){d=0;for(var g=r.querySelectorAll(".dhx_map_line"),_=0;_<g.length;_++)d+=g[_].offsetHeight;d+2<scheduler.config.min_map_size?d=scheduler.config.min_map_size:d+=2}else if(scheduler._gridView)if(d=0,r.childNodes[1].childNodes[0].childNodes&&r.childNodes[1].childNodes[0].childNodes.length){for(var g=r.childNodes[1].childNodes[0].childNodes[0].childNodes,_=0;_<g.length;_++)d+=g[_].offsetHeight;d+=2,d<scheduler.config.min_grid_size&&(d=scheduler.config.min_grid_size);
}else d=scheduler.config.min_grid_size;if(scheduler.matrix&&scheduler.matrix[o])if(e)d+=2,r.style.height=d+"px";else{d=2;for(var x=scheduler.matrix[o],y=x.y_unit,f=0;f<y.length;f++)d+=y[f].children?x.folder_dy||x.dy:x.dy}("day"==o||"week"==o||scheduler._props&&scheduler._props[o])&&(d+=2)}a+=d}scheduler._obj.style.height=a+"px",e||scheduler.updateView()},r=function(){if(!scheduler.config.container_autoresize||!t)return!0;var e=scheduler.getState().mode;l(),(scheduler.matrix&&scheduler.matrix[e]||"month"==e)&&window.setTimeout(function(){
l(!0)},1)};scheduler.attachEvent("onViewChange",r),scheduler.attachEvent("onXLE",r),scheduler.attachEvent("onEventChanged",r),scheduler.attachEvent("onEventCreated",r),scheduler.attachEvent("onEventAdded",r),scheduler.attachEvent("onEventDeleted",r),scheduler.attachEvent("onAfterSchedulerResize",r),scheduler.attachEvent("onClearAll",r),scheduler.attachEvent("onBeforeExpand",function(){return t=!1,!0}),scheduler.attachEvent("onBeforeCollapse",function(){return t=!0,!0})}();
//# sourceMappingURL=../sources/ext/dhtmlxscheduler_container_autoresize.js.map